### PR TITLE
HSEARCH-2182 Configuring plug-in for creating API/SPI change report

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
It's configured to generate a change report for public API/SPI to _engine/target/site_ and _orm/target/site_. Greatly helps with writing the migration notes for the web site.

**Comment by gunnarmorling** [comment]
Migration notes based on the the generated report pushed to http://staging.hibernate.org/search/documentation/migrate/5.6/.

**Comment by Sanne** [comment]
> Migration notes based on the the generated report pushed to http://staging.hibernate.org/search/documentation/migrate/5.6/.

They look great, please push in production

**Comment by Sanne** [comment]
Very nice report, merged it!

**Pull request closed without merging**
