### PR TITLE
HSEARCH-2909 Prevent NPE for annotation w/out package

### PR DESCRIPTION
**Pull request by sbeigel**
See [HSEARCH-2909](https://hibernate.atlassian.net/browse/HSEARCH-2909)

### CODE REVIEW

**Comment by yrodiere** [comment]
ok to test

**Comment by Sanne** [comment]
Nice, thanks @sbeigel ! @yrodiere let's backport this to 5.8 too?

**Comment by yrodiere** [comment]
@sbeigel Thanks!
@Sanne Sure, I'll add a test, merge everything and backport.

**Comment by sbeigel** [comment]
@Sanne I thought about adding a test but I don't know how to get an annotation w/out a (loaded) package...

**Comment by yrodiere** [comment]
@sbeigel No problem, I'm doing it, it'll be quick :) You only need to create an annotation in the top-level (default) package.

**Comment by sbeigel** [comment]
@yrodiere Great, thanks!

**Comment by yrodiere** [comment]
Merged and backported to 5.8. Thanks!

**Pull request merged**
