### PR TITLE
HSEARCH-2535 and HSEARCH-2510 Backport to 5.5

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-2535
https://hibernate.atlassian.net/browse/HSEARCH-2510

### CODE REVIEW

**Comment by Sanne** [comment]
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:[55,62] method createHSQuery in interface org.hibernate.search.spi.SearchIntegrator cannot be applied to given types;
  required: no arguments
  found: org.apache.lucene.search.MatchAllDocsQuery,java.lang.Class<org.hibernate.search.test.query.facet.MultiValuedFacetingTest.StringArrayFacetEntity>
  reason: actual and formal argument lists differ in length
[ERROR] /home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:[82,62] method createHSQuery in interface org.hibernate.search.spi.SearchIntegrator cannot be applied to given types;
  required: no arguments
  found: org.apache.lucene.search.MatchAllDocsQuery,java.lang.Class<org.hibernate.search.test.query.facet.MultiValuedFacetingTest.StringCollectionFacetEntity>
  reason: actual and formal argument lists differ in length
[ERROR] /home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:[109,62] method createHSQuery in interface org.hibernate.search.spi.SearchIntegrator cannot be applied to given types;
  required: no arguments
  found: org.apache.lucene.search.MatchAllDocsQuery,java.lang.Class<org.hibernate.search.test.query.facet.MultiValuedFacetingTest.StringMapFacetEntity>
  reason: actual and formal argument lists differ in length
[ERROR] /home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:[137,62] method createHSQuery in interface org.hibernate.search.spi.SearchIntegrator cannot be applied to given types;
  required: no arguments
  found: org.apache.lucene.search.MatchAllDocsQuery,java.lang.Class<org.hibernate.search.test.query.facet.MultiValuedFacetingTest.NumberArrayFacetEntity>
  reason: actual and formal argument lists differ in length
[ERROR] /home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:[167,62] method createHSQuery in interface org.hibernate.search.spi.SearchIntegrator cannot be applied to given types;
  required: no arguments
  found: org.apache.lucene.search.MatchAllDocsQuery,java.lang.Class<org.hibernate.search.test.query.facet.MultiValuedFacetingTest.NumberCollectionFacetEntity>
  reason: actual and formal argument lists differ in length
[ERROR] /home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:[197,62] method createHSQuery in interface org.hibernate.search.spi.SearchIntegrator cannot be applied to given types;
  required: no arguments
  found: org.apache.lucene.search.MatchAllDocsQuery,java.lang.Class<org.hibernate.search.test.query.facet.MultiValuedFacetingTest.NumberMapFacetEntity>
  reason: actual and formal argument lists differ in length

```

**Comment by Sanne** [comment]
```
[INFO] Starting audit...
/home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:56:46: Found two spaces: '				.luceneQuery(  new MatchAllDocsQuery() )'
/home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:85:46: Found two spaces: '				.luceneQuery(  new MatchAllDocsQuery() )'
/home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:114:46: Found two spaces: '				.luceneQuery(  new MatchAllDocsQuery() )'
/home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:144:46: Found two spaces: '				.luceneQuery(  new MatchAllDocsQuery() )'
/home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:176:46: Found two spaces: '				.luceneQuery(  new MatchAllDocsQuery() )'
/home/sanne/workspaces/hibernate/hibernate-search-root/orm/src/test/java/org/hibernate/search/test/query/facet/MultiValuedFacetingTest.java:208:46: Found two spaces: '				.luceneQuery(  new MatchAllDocsQuery() )'
Audit done.


```

**Comment by yrodiere** [comment]
@Sanne Thanks, it's fixed.

@gsmet The build now passes: https://travis-ci.org/yrodiere/hibernate-search/builds/188861591
I removed the commit that added the .travis.yml.

**Comment by Sanne** [comment]
@Hibernate-CI retest this please

**Pull request merged**
