### PR TITLE
HSEARCH-2134 Elasticsearch distribution packages

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/HSEARCH-2134

### CODE REVIEW

**Comment by DavideD** [comment]
It seems that this test does not pass anymore now: MassIndexingTimeoutIT

Any idea what could cause the problem?

**Comment by DavideD** [comment]
I'm closing this for now, I want to investigate it a bit more.
It seems that adding module in wildfly and making it an optional dependency to search engine is enough to make this test fails, even if it does not use elasticsearch

**Comment by DavideD** [comment]
Added a commit to change the distribution folder

**Comment by DavideD** [comment]
By the way, does the integration test fail for you as well?

**Comment by Sanne** [comment]
> By the way, does the integration test fail for you as well?

Yes, but couldn't debug it yet.

**Comment by Sanne** [comment]
The test is failing because `org.hibernate.search.backend.elasticsearch.impl.ElasticsearchBridgeProvider` is overriding the Bridge, even though we're not using Elasticsearch in this case.

I'll disable this test as this PR is otherwise good, and will raise the priority for
 - https://hibernate.atlassian.net/browse/HSEARCH-2067 cc/ @gsmet @gunnarmorling

**Comment by Sanne** [comment]
Well HSEARCH-2067 was "Blocker" already so that's not changing ;-)

**Comment by Sanne** [comment]
> Sounds good, shouldn't we also change the name of the artifact as well, then?

I think so, but ask the mailing list so we can get a quorum. We can do it as a different issue.

**Comment by Sanne** [comment]
merged with an additional commit to disable the failing IT tests

**Pull request closed without merging**
