### PR TITLE
HSEARCH-4959 Upgrade to ORM 6.3.1 / HSEARCH-4935 Re-enable Spring integration tests after next 6.3 ORM upgrade

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HSEARCH-4959
https://hibernate.atlassian.net/browse/HSEARCH-4935

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]

**Comment by yrodiere** [comment]
The build is failing... MultiTenancyHelper strikes again, it seems.

**Comment by marko-bekhta** [comment]
yeeeeeeeah 😄 
and additional assert was added in this commit refactoring the connection provider https://github.com/hibernate/hibernate-orm/blob/d4accd023317cb429964cb109c0b4162d1ee2675/hibernate-testing/src/main/java/org/hibernate/testing/env/ConnectionProviderBuilder.java 
And we cannot reach the `assumeTrue( dialect instanceof H2Dialect );` to skip the tests since ORM tries to open a connection to create a dialect... I've added a property `hibernate.temp.use_jdbc_metadata_defaults` to the helper that should prevent ORM from going to DB ... alternatively... we could wrap `ConnectionProvider connectionProvider = ConnectionProviderBuilder.buildConnectionProvider( tenantId );` into try-catch and if we catch an assert error we can "assume that test is only applicable for h2 DBs and we are running on non h2 one" ...

**Comment by yrodiere** [comment]
> I've added a property hibernate.temp.use_jdbc_metadata_defaults to the helper that should prevent ORM from going to DB ...

Makes sense. It will probably break someday, but we can improvise when that happens.

> we could wrap ConnectionProvider connectionProvider = ConnectionProviderBuilder.buildConnectionProvider( tenantId ); into try-catch and if we catch an assert error we can "assume that test is only applicable for h2 DBs and we are running on non h2 one" ...

No thanks :D 

I guess another alternative would be to have a look at how such assumptions are implemented in the SkipForDialect/RequiresDialect annotations in hibernate testing. But if your current solution work, let's stick to that.

**Comment by marko-bekhta** [comment]
> I guess another alternative would be to have a look at how such assumptions are implemented in the SkipForDialect/RequiresDialect annotations in hibernate testing

That was a nice suggestion 😃; since there's that utility `DialectContext.getDialect()`, this approach seems cleaner since we wouldn't even try to go through builder methods in this case.

**Review by yrodiere — APPROVED** [review]

**Pull request merged**
