### PR TITLE
HSEARCH-4043/4095 Remove Byteman from RestartChunkIT and fix package names

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4043
https://hibernate.atlassian.net/browse/HSEARCH-4095

### CODE REVIEW

**Review by yrodiere — COMMENTED** [review]
Looks good! Two comments:

1. A `SimulatedFailure.reset()` would spare us some headaches in the future.
2. I believe you didn't actually remove the Byteman dependency from the POM files?

**Comment by yrodiere** [comment]
By the way, the problems reported by Sonar will be fixed once you rebase on the `master` branch.

**Comment by fax4ever** [comment]
@yrodiere thanks for the review! Good idea to clean up the state before each test, I added a commit for it.

**Comment by fax4ever** [comment]
From my understanding the Byteman dependency is acquired through `org.hibernate:hibernate-testing` module:

``` bash
[INFO] |  \- org.hibernate:hibernate-testing:jar:5.4.23.Final:test
[INFO] |     +- junit:junit:jar:4.13.1:test
[INFO] |     |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |     +- org.jboss.byteman:byteman:jar:4.0.13:test
[INFO] |     +- org.jboss.byteman:byteman-install:jar:4.0.13:test
[INFO] |     +- org.jboss.byteman:byteman-bmunit:jar:4.0.13:test
[INFO] |     |  \- org.jboss.byteman:byteman-submit:jar:4.0.13:test
[INFO] |     +- com.experlog:xapool:jar:1.5.0:test
[INFO] |     \- org.jboss.jbossts:jbossjta:jar:4.16.4.Final:test
```

**Review by yrodiere — APPROVED** [review]
LGTM, feel free to merge once the CI build passes. Thanks!

**Comment by fax4ever** [comment]
Thank you!

**Pull request merged**
