### PR TITLE
HSEARCH-2214 Only wait for status "yellow" after index creation

### PR DESCRIPTION
**Pull request by gunnarmorling**
[HSEARCH-2214](https://hibernate.atlassian.net/browse/HSEARCH-2214).

### CODE REVIEW

**Comment by Sanne** [comment]
No I don't think we can accept to write on "yellow" by default.
HSEARCH-2214 reads: Provide **an option** to wait for Elasticsearch status yellow rather than green

If people want to set some "unsafe" option and disable seatbelts, that's their problem.. but safe defaults should be our responsibility.

**Comment by gunnarmorling** [comment]
Did you see my last comment on the Jira issue? How would you deal with
status degradation after start-up? I had hoped we'd quickly agree, but if
not, let's have a discussion over there.

**Comment by Sanne** [comment]
> Did you see my last comment on the Jira issue?

Saw it now, sorry for the delay :-/ replied..

happy to pick up the phone it it helps? I feel like my very question about the property is important but still ignored by all replies..

**Comment by gunnarmorling** [comment]
@Sanne pushed an update, making it an option as discussed. The question is how to test it in an automated fashion (I've done some manual testing which looked good). We'd likely need a separate _elasticsearch.yml_ and thus a separate execution of the ES Maven plug-in. Doable, but it'll take time. Should we go for it?

**Comment by DavideD** [comment]
I'm OK to post-pone the testing using a separate configuration for now and
create a separate JIRA so that we don't forget to add it later.

**Comment by gunnarmorling** [comment]
Rebased and force-pushed an update to cover the new property in docs, too.

**Comment by Sanne** [comment]
too late! I had just merged it, and was about to open a jira to track the need for docs..

**Comment by Sanne** [comment]
cool, all merged. Seemed you had rebased on your own changes so it was linear still :)

**Pull request merged**
