### PR TITLE
HSEARCH-2607 Improve OSGi test diagnostics when running tests on misc…

### PR DESCRIPTION
**Pull request by Sanne**
…onfigured networks

See also:
 - https://github.com/hibernate/hibernate-search/pull/1331
 - https://hibernate.atlassian.net/browse/HSEARCH-2607

### CODE REVIEW

**Comment by yrodiere** [comment]
Build failing:

```
[ERROR] /mnt/jenkins-workdir/workspace/hibernate-search-PR/integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/SystemTest.java:28:40: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
[ERROR] /mnt/jenkins-workdir/workspace/hibernate-search-PR/integrationtest/osgi/karaf-it/src/test/java/org/hibernate/search/test/integration/osgi/SystemTest.java:31:40: String literal expressions should be on the left side of an equals comparison. [EqualsAvoidNull]
```

**Comment by Sanne** [comment]
Looks like I underestimated the complexity of implementing this check :)

fixed

**Comment by Sanne** [comment]
Looks like the AWS slaves need reconfiguring as well:
 
    local machine name 'ip-172-30-1-189.ec2.internal' needs to resolve to a localhost address, most commonly as '127.0.0.1' or '127.0.1.1'. It resolved to: '172.30.1.189'. Fix your network configuration to be able to run the OSGi integration tests reliably. (It is possible though that OSGi tests will pass even if this fails.)

**Comment by Sanne** [comment]
Pushed a new approach ... this should cause less trouble :-D

**Comment by yrodiere** [comment]
Looks much safer indeed :grin:
Merged, thanks!

**Pull request merged**
