### PR TITLE
HSEARCH-1783, HSEARCH-1474 Making mass indexer transaction timeout configurable

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by Sanne** [comment]
I've pushed your second commit already, in case you're up for making some more changes.
Still playing with the main stuff :)

**Comment by gunnarmorling** [comment]
Jenkins, retest this please.

**Comment by gunnarmorling** [comment]
@Sanne, force-pushed to address your remarks regarding Arquillian, the spec artifacts and the way of pulling in HS.

**Comment by gunnarmorling** [comment]
@Sanne, added one more commit to make the timeout configurable and apply it to the transactions opened by the mass indexer in JTA environments.

**Comment by gunnarmorling** [comment]
Jenkins, retest this please.

**Comment by Sanne** [comment]
Merged, great!

I created a separate issue for the dependency cleanup you did for other ITs (it's solved).

**Pull request closed without merging**
