### PR TITLE
HSEARCH-2270 Upgrade to Apache Lucene 5.5.1.Final

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HSEARCH-2270

### CODE REVIEW

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-search/pull/1102

**Comment by DavideD** [comment]
@Sanne I merged this on master, should I merge it somewhere else?

**Comment by Sanne** [comment]
Yeah, could you push it to 5.5 as well please?
Or I can do it later, I'm travelling again :/

**Comment by DavideD** [comment]
When I apply it to the branch 5.5 I have some exception.
Could you have a look at it?

**Comment by Sanne** [comment]
my bad, I keep thinking that branch 5.5 is using the same Lucene but it's on version 5.3.x and we can't update that.

**Pull request closed without merging**
