### PR TITLE
HSEARCH-2126 Checkstyle fails when explicitly called via goal checkstyle:check

### PR DESCRIPTION
**Pull request by s4ke**
@gsmet: can you run this on your machine as well?

### CODE REVIEW

**Comment by gsmet** [comment]
I still have an error
```
[ERROR] /data/home/gsmet/git/gsmet/hibernate-search/orm/src/test/resources/org/hibernate/search/test/spatial/hibernate.cfg.xml:1: Line does not match expected header line of '<?xml version="1.0" encoding="UTF-8"?>'. [Header]
```

utf-8 should be UTF-8 in the header. Once this one is fixed, it works OK.

**Comment by s4ke** [comment]
I added some additional fixes that showed up (for some reason).

**Comment by Sanne** [comment]
We never meant to run checkstyle on XML files. The formatting improvements in these changed XML look fine, but do we want to enforce it on XML?

**Comment by gsmet** [comment]
I don't have a strong opinion about it but it doesn't look like too much of a hassle.

Just wanted to have checkstyle:check working.

**Comment by s4ke** [comment]
@Sanne:

Well, I haven't added any rules regarding xml. Also, this

`<module name="Header">
        <property name="header" value="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;\n&lt;!--\n ~ Hibernate Search, full-text search for your domain model\n ~\n ~ License: GNU Lesser General Public License (LGPL), version 2.1 or later\n ~ See the lgpl.txt file in the root directory or &lt;http://www.gnu.org/licenses/lgpl-2.1.html&gt;.\n  --&gt;"/>
        <property name="fileExtensions" value="xml"/>
    </module>`

suggests that at some point this was intended.

**Comment by s4ke** [comment]
@Sanne: bump

**Comment by Sanne** [comment]
yes we can merge this, but beware I think people will eventually make XML formatting mistakes and the regular build wouldn't catch it (the same way it didn't catch these before).

Could we adjust this to make sure the `checkstyle:check` coverage is the same as when doing a normal (full) build?

**Comment by s4ke** [comment]
Errors in .xml files are also reported during a normal build, but as it seems the default behaviour has changed. We could just disable all checkstyle checks on .xml files apart from the header check, this would do it as well, right?

**Comment by s4ke** [comment]
@Sanne : i changed it so only the Header check is run on xml files.

**Comment by Sanne** [comment]
@s4ke try this: remove the header from one of the files you fixed, then run the build again. It won't complain...

That's what I meant by saying that it's not regression-proof.

Sure, it's an improvement in style but I'm pretty sure it won't last if it's not automatically prevented ;)

If you want I can merge this.. not a problem. Just saying that if we could enable the automatic check as well, then you'll have solved the problem for longer term.

**Comment by Sanne** [comment]
This is what I'm testing:
 - I fetch your branch
 - I revert your commit 3541607
 - I run `mvn clean install`

I would expect it to fail, but it's not. Am I running the wrong Maven goal?

BTW please squash 2232f66c4f74c7c58f6e547564139274f1975086 into its parent ;)

**Comment by s4ke** [comment]
@Sanne:

During the build checkstyle:checkstyle is used which generates reports. For some reason this apparently behaves differently to checkstyle:check when it comes to error checking.

**Comment by Sanne** [comment]
Awesome, seems you untangled the mystery :+1: 

Merged

**Pull request closed without merging**
