### PR TITLE
HSEARCH-2328 Allow inclusion of source code in the documentation

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/HSEARCH-2328

I've added a couple of entities in the "Getting Started" section to test that it works.
It's safe to exclude the related commit (https://github.com/hibernate/hibernate-search/commit/8892ed37cb847a2113c0345c9e9bcfec01e627d5) if we want to keep the doc clear.

### CODE REVIEW

**Comment by yrodiere** [comment]
Jenkins, retest this please

**Comment by yrodiere** [comment]
Jenkins, retest this please

**Comment by yrodiere** [comment]
Jenkins, retest this please

**Comment by yrodiere** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Added a simple test case with GeoPolygon class (the simpler one I found)

**Comment by yrodiere** [comment]
Thanks! I removed a few unnecessary dependencies (you really only need the backend, the mapper, and the test utils, everything else will be pulled transitively), rebased and merged.

**Pull request merged**
