### PR TITLE
HSEARCH-2594 JSR-352 (Batch) integration

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-2594

This adds JSR-352 integration through two publicly exposed modules:

 * `hibernate-search-jsr352-core`, which contains all runtime-independent code (and happens to be enough for the JBatch reference implementation)
 * `hibernate-search-jsr352-jberet`, which adds jberet-specific glue, mainly related to CDI (which is not mandatory for JSR-352 runtimes)

There are a few remaining sub-tasks, but I think I'll move them to independent tickets once this PR has been merged, because they are not critical: https://hibernate.atlassian.net/issues/?jql=parent%20%3D%20HSEARCH-2594%20and%20resolution%20is%20empty%20ORDER%20BY%20status%20DESC

Note that there are quite a lot of commits, but I already tried my best to squash commits together and remove merge commits (I removed all merge commits), while still preserving authorship information and avoiding huge commits that nobody will undestand.

I added performance tests as part of this PR. Results are available here: http://ci.hibernate.org/view/Search/job/hibernate-search-performance-orm/. See in particular how the `FileSystemSessionMassIndexer` and `FileSystemJsr352MassIndexer` scenarios resulted in similar execution times.

To make your review as painless as possible, I would recommend to proceed like this:

 * Read the documentation (`manual-index.asciidoc`, marker `jsr352-integration`). If it's not clear how to use it after that, we probably have to work on it.
 * Have a look at integration tests:
   * `org.hibernate.search.jsr352.massindexing.BatchIndexingJobIT#simple`
   * `org.hibernate.search.jsr352.massindexing.BatchIndexingJobIT#criteria`
   * `org.hibernate.search.jsr352.massindexing.BatchIndexingJobIT#hql`
   * `org.hibernate.search.jsr352.massindexing.BatchIndexingJobIT#partitioned`
   * `org.hibernate.search.jsr352.massindexing.RestartChunkIT#failureDuringFirstCheckpointBetweenTwoWrites_fullScope`
 * Read the architecture description in `jsr352/README.md`
 * Dive into the full diff... Reviewing commit by commit will probably be way too much work.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Woah, great news to see it finally land in HSEARCH proper. Really excited
about it, great achievement by Mincong, Yoann et al!

Thanks!!!

**Comment by mincong-h** [comment]
Thank you @yrodiere for all your contributions and helps of this contribution :muscle: :muscle: :clap: :clap:

**Comment by yrodiere** [comment]
@mincong-h Thanks to you for your work! I know that JSR-352 can be full of surprises, not all of which are pleasant ones ;)
But let's wait for the review before we celebrate :)

**Comment by Sanne** [comment]
Awesome job everyone! I plan to dedicate a couple of days next week to playing with this.

**Comment by Sanne** [comment]
It's merged! Awesome job everyone 💯

**Pull request closed without merging**
