### PR TITLE
HSEARCH-1875 Upgrade to JBoss Byteman 3.0.0

### PR DESCRIPTION
**Pull request by hferentschik**
Supersedes #830

### CODE REVIEW

**Comment by Sanne** [comment]
I don't understand. It's exactly the same as #830 , so why replace the other PR?

**Comment by Sanne** [comment]
@hferentschik This was failing for @gunnarmorling . Gunnar could you try it again and/or share some details?

**Comment by hferentschik** [comment]
> I don't understand. It's exactly the same as #830 , so why replace the other PR?

This is re-based and merge conflicts resolved.

**Comment by Sanne** [comment]
> This is re-based and merge conflicts resolved.

Ah, thanks! I thought there was some magic fix for Mac included :)

**Comment by gunnarmorling** [comment]
> @hferentschik This was failing for @gunnarmorling . Gunnar could you try it again and/or share some details?

It was failing on CI, not locally for me. As this PR passes now (I guess due to the rebase and changes since then?), I will merge it.

**Comment by Sanne** [comment]
great! Sorry for the confusion gunnar. I though you mentioned some different issue over irc.

**Pull request merged**
