### PR TITLE
HSEARCH-2991 Avoid needing jsr250-api during project build

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HSEARCH-2991

### CODE REVIEW

**Comment by yrodiere** [comment]
@Sanne I just tried it, and the `@Generated` annotation still gets generated:

```java
/**
 * Warning this class consists of generated code.
 */
@Generated(value = "org.jboss.logging.processor.generator.model.MessageLoggerImplementor", date = "2018-01-23T14:20:13+0100")
public class BaseHibernateSearchLogger_$logger extends DelegatingBasicLogger implements BaseHibernateSearchLogger, BasicLogger, Serializable {
    private static final long serialVersionUID = 1L;
    private static final String FQCN = BaseHibernateSearchLogger_$logger.class.getName();
```

Or was it about another `@Generated` annotation, from another package than `javax.annotation`?

**Comment by gsmet** [comment]
Nope, it's this very one.

**Comment by Sanne** [comment]
Thanks for checking :) It worked in JDK9 but that's for other reasons: it automatically apply "the right" kind of Generated annotation now.

Fixed the PR, a I still want to get rid of this for the sake of tooling.

**Comment by yrodiere** [comment]
Merged, thanks!

**Pull request merged**
