### PR TITLE
HSEARCH-1803 Infinispan Integration test

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/HSEARCH-1803

### CODE REVIEW

**Comment by Sanne** [comment]
@emmanuelbernard could you run this test please? I suspect it won't work on OSX

**Comment by emmanuelbernard** [comment]
@DavideD @Sanne 
Hibernate Search Wildfly Integration Tests are failing

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.hibernate.search.test.integration.cmp.ContainerManagedPersistenceWithMassIndexerIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.901 sec - in org.hibernate.search.test.integration.cmp.ContainerManagedPersistenceWithMassIndexerIT
Running org.hibernate.search.test.integration.jms.infinispan.SearchNewEntityJmsMasterSlaveUsingInfinispanAndModulesIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.963 sec - in org.hibernate.search.test.integration.jms.infinispan.SearchNewEntityJmsMasterSlaveUsingInfinispanAndModulesIT
Running org.hibernate.search.test.integration.jms.SearchNewEntityJmsMasterSlaveIT
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.977 sec - in org.hibernate.search.test.integration.jms.SearchNewEntityJmsMasterSlaveIT
Running org.hibernate.search.test.integration.jms.SearchNewEntityJmsMasterSlaveUsingModulesIT
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.685 sec - in org.hibernate.search.test.integration.jms.SearchNewEntityJmsMasterSlaveUsingModulesIT
Running org.hibernate.search.test.integration.wildfly.InfinispanModuleMemberRegistrationIT
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.609 sec <<< FAILURE! - in org.hibernate.search.test.integration.wildfly.InfinispanModuleMemberRegistrationIT
testSearch(org.hibernate.search.test.integration.wildfly.InfinispanModuleMemberRegistrationIT)  Time elapsed: 0.29 sec  <<< FAILURE!
java.lang.AssertionError: Member inserted by container 1 not found
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.hibernate.search.test.integration.wildfly.InfinispanModuleMemberRegistrationIT.testSearch(InfinispanModuleMemberRegistrationIT.java:122)

Running org.hibernate.search.test.integration.wildfly.MemberRegistrationEarArchiveIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.248 sec - in org.hibernate.search.test.integration.wildfly.MemberRegistrationEarArchiveIT
Running org.hibernate.search.test.integration.wildfly.MemberRegistrationIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.13 sec - in org.hibernate.search.test.integration.wildfly.MemberRegistrationIT
Running org.hibernate.search.test.integration.wildfly.ModuleMemberRegistrationEarArchiveIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.983 sec - in org.hibernate.search.test.integration.wildfly.ModuleMemberRegistrationEarArchiveIT
Running org.hibernate.search.test.integration.wildfly.ModuleMemberRegistrationEarArchiveWithJbossDeploymentIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.077 sec - in org.hibernate.search.test.integration.wildfly.ModuleMemberRegistrationEarArchiveWithJbossDeploymentIT
Running org.hibernate.search.test.integration.wildfly.ModuleMemberRegistrationIT
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.81 sec - in org.hibernate.search.test.integration.wildfly.ModuleMemberRegistrationIT

Results :

Failed tests:
  InfinispanModuleMemberRegistrationIT.testSearch:122 Member inserted by container 1 not found

Tests run: 38, Failures: 1, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-checkstyle-plugin:2.12.1:checkstyle (check-style) @ hibernate-search-integrationtest-wildfly ---
[INFO] Starting audit...
Audit done.

[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO]
[INFO] --- maven-failsafe-plugin:2.17:verify (default) @ hibernate-search-integrationtest-wildfly ---
[INFO] Failsafe report directory: /Users/emmanuel/Code/search/integrationtest/wildfly/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Hibernate Search Aggregator ........................ SUCCESS [  0.606 s]
[INFO] Hibernate Search Build Configuration ............... SUCCESS [  3.034 s]
[INFO] Hibernate Search Engine ............................ SUCCESS [ 17.959 s]
[INFO] Hibernate Search ORM ............................... SUCCESS [01:02 min]
[INFO] Hibernate Search [Deprecated Module] ............... SUCCESS [  0.055 s]
[INFO] Hibernate Search Java Default Serialization ........ SUCCESS [  0.879 s]
[INFO] Hibernate Search Avro Serialization ................ SUCCESS [  2.735 s]
[INFO] Hibernate Search JGroups Backend ................... SUCCESS [  7.699 s]
[INFO] Hibernate Search JMS Backend ....................... SUCCESS [  0.683 s]
[INFO] Hibernate Search Testing ........................... SUCCESS [  0.502 s]
[INFO] Hibernate Search Infinispan Directory Provider ..... SUCCESS [ 14.276 s]
[INFO] Hibernate Search Wildfly Module .................... SUCCESS [  0.955 s]
[INFO] Hibernate Search JMS Integration Tests ............. SUCCESS [  5.045 s]
[INFO] Hibernate Search Narayana Integration Tests ........ SUCCESS [  2.362 s]
[INFO] Hibernate Search Spring Integration Tests .......... SUCCESS [  8.641 s]
[INFO] Hibernate Search Wildfly Integration Tests ......... FAILURE [01:16 min]
[INFO] Hibernate Search Performance Tests ................. SKIPPED
[INFO] Hibernate Search Karaf Features Definition ......... SKIPPED
[INFO] Hibernate Search Sandbox Performance Tests ......... SKIPPED
[INFO] Hibernate Search Manual ............................ SKIPPED
[INFO] Hibernate Search OSGi Karaf Integration Tests ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:25 min
[INFO] Finished at: 2015-02-09T11:05:18+01:00
[INFO] Final Memory: 83M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:verify (default) on project hibernate-search-integrationtest-wildfly: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/emmanuel/Code/search/integrationtest/wildfly/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hibernate-search-integrationtest-wildfly
```

**Comment by DavideD** [comment]
@Sanne you seem to know the reason. Can you point to an article, issue or discussion about it?

To me it seems that it is not possible to use Infinispan on OSX.

**Comment by Sanne** [comment]
thanks.
I'm closing this PR, and will incorporate it in a PR (as I need to rebase as well).. just adding a small change then we try again.

**Comment by Sanne** [comment]
Followed up with PR #797

**Pull request closed without merging**
