### PR TITLE
HSEARCH-2245 Fix URL to the delete-by-query plugin

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-search/pull/1092

Thanks

**Comment by DavideD** [comment]
Is the JIRA issue number correct?

**Comment by gsmet** [comment]
Argh no, got it wrong :/

**Comment by gsmet** [comment]
The right issue is this one: https://hibernate.atlassian.net/browse/HSEARCH-2156 .

I closed it.

**Pull request merged**
