### PR TITLE
HSEARCH-1954 Solve issue with JDK 8

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/HSEARCH-1954

This pull request changes all the javadocs that are causing exceptions during the javadoc generation.
It also enforce the use of JDK 8,

I'm still not sure how we plan to check if everything works with JDK7 without the creation of a separate project.

I will update the wiki and the website if the pull is merged.

### CODE REVIEW

**Comment by Sanne** [comment]
The first replacement went wrong: surname is not "Bernard>"

**Comment by Sanne** [comment]
on top of the very minor comments I made above, there are a couple more tasks to be done:

### profiles cleanup
some profiles get only activate on minimum JDK8, these could be simplified (not longer need them as a profile, default would be good enough).

### Wiki updates
The how-to-contribute wikis and the "how to release" wikis need to be updated.

### Jenkins jobs
We'll have to disable the JDK7 specific jobs, and reconfigure the "main" jobs to use JDK8. Better to do that before we merge it to prevent failure notifications.

**Comment by Sanne** [comment]
@DavideD I'll do the website updates and the Jenkins jobs.. can you update this PR related to the other things?

Optional: do you think there's some good part in these (thinking javadoc fixes) which we could apply to 5.4 w/o too much trouble? worth trying?

**Comment by DavideD** [comment]
> @DavideD I'll do the website updates and the Jenkins jobs.. can you update this PR related to the other things?

Yep, thanks

> Optional: do you think there's some good part in these (thinking javadoc fixes) which we could apply to 5.4 w/o too much trouble? worth trying?

Except for the last 2 commits, all the changes are related to the javadocs, so I'm not expecting to many issues.  I'll try it

**Comment by DavideD** [comment]
I've applied the changes and rebased:
* Fix author for Emmanuel
* Fix changes to the pom alignement
* Integration tests with WildFly are now part of the default build

**Comment by Sanne** [comment]
Thanks, CI jobs should be updated.. merged it, let's see the build outcomes.

**Pull request merged**
