### PR TITLE
HSEARCH-2430 Update checkstyle ParenPad rule to include RESOURCE_SPEC…

### PR DESCRIPTION
**Pull request by Sanne**
…IFICATION

 - https://hibernate.atlassian.net/browse/HSEARCH-2430

### CODE REVIEW

**Comment by yrodiere** [comment]
Did you check that our Eclipse code formatting settings are consistent with this new rule?
I just tried my IntelliJ settings (originally taken from the IDEA OGM settings) and no spaces are added. I can create/update the IntelliJ settings for Search, but it'd be great if you could take care of Eclipse, if you use it.

**Comment by Sanne** [comment]
Good point, I'll check it. But I wouldn't consider that a "pre-requisite" .. no IDE formatting settings has ever been 100% consistent with our checkstyle rules (not that I wouldn't wish that - just hasn't been the case).

**Comment by yrodiere** [comment]
Merged and submitted a PR to update the code styles: https://github.com/hibernate/hibernate-ide-codestyles/pull/5
Thanks!

**Comment by Sanne** [comment]
@rnveach we don't run "mvn checkstyle:check" but we just run "mvn verify", as checkstyle is normally enabled for all modules.
It looks like it's not currently enabled for `hibernate-search-jsr352-core` so I failed to see these style issues.

Thanks for pointing it out, I'll fix them now :+1:

**Comment by Sanne** [comment]
@rnveach feel free to watch https://hibernate.atlassian.net/browse/HSEARCH-3001

We'll merge it soon, likely tomorrow.

Thanks again for highlighting our build problem!

**Comment by rnveach** [comment]
No problem. Thanks for the fix.

**Pull request merged**
