### PR TITLE
Create hibernate-search feature pack

### PR DESCRIPTION
**Pull request by ctomc**
@Sanne lets talk about this.

There is also second part on wildfly build side that i am still working on.
WIP branch for inclusion in wildfly https://github.com/ctomc/wildfly/tree/hsearch-feature-pack

### CODE REVIEW

**Comment by ctomc** [comment]
@Sanne https://github.com/ctomc/wildfly/tree/hsearch-feature-pack

**Comment by hferentschik** [comment]
ok to test

**Comment by Sanne** [comment]
I love the general approach, but since we can't expect to have a strong 1:1 relation in Hibernate Search releases and WildFly releases, I've sent an email to wildfly-dev to discuss what strategies we should use to have different slots (module versions).

**Comment by Sanne** [comment]
Some progress, at least in terms of thoughts:
 - http://lists.jboss.org/pipermail/wildfly-dev/2015-April/003787.html
 - http://lists.jboss.org/pipermail/wildfly-dev/2015-May/thread.html

**Comment by ctomc** [comment]
any news on this? it would be great if we could get this done for WF10

**Comment by gastaldi** [comment]
Wildfly Swarm requires a valid feature pack ZIP file in order to create a fraction. See https://hibernate.atlassian.net/browse/HSEARCH-2191

**Comment by Sanne** [comment]
We've split most of such modules out, and are in the process of converting them all into quite "fine-grained" feature packs.

The Apache Lucene one is merged:
 - https://github.com/hibernate/lucene-jbossmodules

others will follow up shortly. Closing this PR as it's now obsolete, but thanks again all of you as this has been very useful guidance and a good example to start from!

**Pull request closed without merging**
