### PR TITLE
HSEARCH-2337 Async backend not properly flushed

### PR DESCRIPTION
**Pull request by gustavonalle**
https://hibernate.atlassian.net/browse/HSEARCH-2337

### CODE REVIEW

**Comment by gustavonalle** [comment]
One issue I caught is after calling ```flushAndReleaseResources``` in the the async backend, the scheduler that commits at regular intervals will still be operational, when ideally is should not. I will update the PR shortly.

**Comment by Sanne** [comment]
thanks @gustavonalle . We have a release today, I'll wait for your fix.

**Comment by gustavonalle** [comment]
Ready for review.

**Comment by Sanne** [comment]
Thanks, it looks good except an unlikely race between stopping/starting the same backend.. I already have a local fix so don't worry about it. Testing, then will merge.

Thanks!

**Comment by Sanne** [comment]
merged

**Pull request closed without merging**
