### PR TITLE
HSEARCH-4374 Make outbox-polling ITs shorter, in particular automatic indexing ITs

### PR DESCRIPTION
**Pull request by yrodiere**
* [HSEARCH-4374](https://hibernate.atlassian.net/browse/HSEARCH-4374): Make outbox-polling ITs shorter, in particular automatic indexing ITs

Based on #2711 , which should be merged first.

### CODE REVIEW

**Comment by yrodiere** [comment]
Build against all databases: https://ci.hibernate.org/job/hibernate-search/job/PR-2712/8/

**Comment by fax4ever** [comment]
Re-run the build for an expected Ec2 issue on the previous one: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2712/9/pipeline

**Review by fax4ever — APPROVED** [review]
LGTM, thank you!

**Comment by yrodiere** [comment]
Execution time before my patch:

```
[INFO] Hibernate Search ITs - ORM ......................... SUCCESS [01:39 min]
[INFO] Hibernate Search ITs - ORM - Coordination - Outbox Polling SUCCESS [07:27 min]
```

After my patch:

```
[INFO] Hibernate Search ITs - ORM ......................... SUCCESS [01:29 min]
[INFO] Hibernate Search ITs - ORM - Coordination - Outbox Polling SUCCESS [01:56 min]
```

Still slow, but definitely much more reasonable, and much more in line with the duration of "classic" tests (those without the `outbox-polling` coordination strategy).

**Comment by yrodiere** [comment]
The CI failure is unrelated (see https://hibernate.zulipchat.com/#narrow/stream/132095-hibernate-infra/topic/Jenkins.20nodes.20getting.20removed ) ; merging. Thanks!

**Pull request merged**
