### PR TITLE
HSEARCH-4756 Use more timezone IDs in TCK tests

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HSEARCH-4756

### CODE REVIEW

**Comment by yrodiere** [comment]
CI timed out... I suspect all timezone IDs is a lot of timezone IDs?

**Comment by marko-bekhta** [comment]
hmmmm, it's only `602` for me locally 😃 I've tried a few tests locally and it didn't take that much longer than before. Running a full tck build to see what'll happen and if there's some test where it gets stuck.

**Comment by marko-bekhta** [comment]
Seem those loops were for something like query single doc by id or something? can't see why we want to keep them though 😃

**Review by yrodiere — APPROVED** [review]

**Comment by marko-bekhta** [comment]
hmm so the failing timezones are:
```
307=1900-01-01T00:00+07:21:20[Asia/Kuching]
507=1900-01-01T00:00+07:39:40[Asia/Brunei]
```
and `Europe/Amsterdam` is also on the list
```
450=1900-01-01T00:00+00:19:32[Europe/Amsterdam]
```
I was somewhat expecting that those "broken" timezones won't be on the list

**Comment by yrodiere** [comment]
Alright. Maybe let's hardcode a few exotic ones and leave it at that? Since the failures are not in Hibernate Search itself (unless it's a different problem?)

**Review by yrodiere — APPROVED** [review]

**Pull request merged**
