### PR TITLE
HSEARCH-2145 Fix NPE when running checkstyle:check

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by s4ke** [comment]
Can you provide me with a snippet so I can confirm the NPE behaviour?

**Comment by gsmet** [comment]
I just run mvn checkstyle:check on the tree. 

That being said I'm wondering if it might be due to the checkstyle upgrade and if a mvn install before running the check would have fixed it.

**Comment by gsmet** [comment]
Confirmed.

@Sanne should we still commit this to make our check consistent with the official checkstyle ones?

If not, I'll close it.

**Comment by Sanne** [comment]
looks good, merged!

**Pull request merged**
