### PR TITLE
HSEARCH-2677 Upgrade to Byteman 4.0.0-BETA3 to restore Java 9 compati…

### PR DESCRIPTION
**Pull request by Sanne**
…bility

 - https://hibernate.atlassian.net/browse/HSEARCH-2677

### CODE REVIEW

**Comment by yrodiere** [comment]
It seems there are problems with this version of Byteman: the build fails, and it's not the usual performance issue. See  http://ci.hibernate.org/job/hibernate-search-PR/org.hibernate$hibernate-search-orm/2066/testReport/junit/org.hibernate.search.test.query.initandlookup/CriteriaObjectInitializerAndHierarchyInheritanceTest/testJoinsAreOnlyOnUsefulEntityTypes/

**Comment by Sanne** [comment]
Interesting, I have been keeping this upgrade locally for a long time and simply thought it was time to merge, as I never had a problem with it. 
Thanks I'll look at it.

**Comment by Sanne** [comment]
My bad, it consistently fails locally as well.
Reported the regression to Byteman: https://issues.jboss.org/browse/BYTEMAN-338

I'll figure out a workaround.

**Comment by Sanne** [comment]
Byteman 4 Beta4 was released to solve our problem :)

Rebased

**Pull request merged**
