### PR TITLE
HSEARCH-2595 Upgrade to Hibernate ORM 5.2.8.Final

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HSEARCH-2595

### CODE REVIEW

**Comment by yrodiere** [comment]
Seems integration tests are failing, we should have a look...

**Comment by Sanne** [comment]
retest this please

**Comment by Sanne** [comment]
It failed because there's a WildFly instance running on CI which wasn't property terminated by some other job.
It works locally; you can ignore it.

**Comment by yrodiere** [comment]
Thanks; merged.

**Pull request merged**
