### PR TITLE
HSEARCH-1901 initialize the Tika AutoDetectParser once per TikaBridge instance

### PR DESCRIPTION
**Pull request by brmeyer**
While profiling Artificer, hit this.  Initializing Tika's AutoDetectParser turns out to be a fairly expensive operation.  Only do it once.

### CODE REVIEW

**Comment by hferentschik** [comment]
Thanks @brmeyer. Could I ask you to

* Create a matching SEARCH issue and refer to it in the commit message
* Fix the checkstyle violations:

    [INFO] Starting audit...
    /var/lib/jenkins/workspace/hibernate-search-PR/engine/src/main/java/org/hibernate/search    /bridge/builtin/TikaBridge.java:43:1: Found two spaces: '    // Expensive, so only do     it once...'
    /var/lib/jenkins/workspace/hibernate-search-PR/engine/src/main/java/org/hibernate/search    /bridge/builtin/TikaBridge.java:44: Line has leading space characters; indentation     should be performed with tabs only.
    /var/lib/jenkins/workspace/hibernate-search-PR/engine/src/main/java/org/hibernate/search    /bridge/builtin/TikaBridge.java:44:1: Found two spaces: '    private static final     Parser PARSER = new AutoDetectParser();'
    /var/lib/jenkins/workspace/hibernate-search-PR/engine/src/main/java/org/hibernate/search    /bridge/builtin/TikaBridge.java:114: Line has leading space characters; indentation     should be performed with tabs only.
    /var/lib/jenkins/workspace/hibernate-search-PR/engine/src/main/java/org/hibernate/search    /bridge/builtin/TikaBridge.java:114:1: Found two spaces: '            PARSER.parse( in,     contentHandler, metadata, parseContext );'
    Audit done.

**Comment by brmeyer** [comment]
> I'd prefer just an instance per bridge
Fair enough -- will correct.

> Could I ask you to
Yep, will do ASAP.

**Comment by brmeyer** [comment]
Done

**Comment by Sanne** [comment]
Thanks! merged it, with a couple very minor changes:
 - avoid the shuffling of import statements
 - add a note about the Parser being safe to use concurrently
 - made PARSER lowercase since its not static

**Pull request closed without merging**
