### PR TITLE
HSEARCH-2479: Changed Hashmap in ConnectedMultiFieldsPhraseQueryBuild…

### PR DESCRIPTION
**Pull request by ttretter**
…er to TreeMap to keep the correct order of search terms.

### CODE REVIEW

**Comment by yrodiere** [comment]
Jenkins, add to whitelist

**Comment by yrodiere** [comment]
@ttretter Thanks for taking the time to fix this!

Do you think you could also add a test? This would make the issue more obvious, and most importantly would prevent regression if we happen to change that class later.

You can add your test in `org.hibernate.search.test.query.dsl.DSLTest`, in the `hibernate-search-orm` module. You can copy/paste `.testPhraseQuery()`, for instance, and adapt the code to reproduce this particular issue.

**Comment by Sanne** [comment]
This is probably too late for next Beta of 5.6 but I'm happy to release a 5.5 bugfix release later this week, just for this fix. Thanks!

**Comment by gsmet** [comment]
@ttretter Hi Timo! Any chance you could inject your test case in DSLTest as mentioned by @yrodiere ?

It would be nice if you could also sign the CLA for the **Hibernate** project on https://cla.jboss.org/index.seam (it's a very simple formality) and come back to us with your username once done.

Thanks!

**Comment by ttretter** [comment]
@gsmet Hi Guillaume,
I've just added the testcase to the pull request (add removed some whitespaces afterwards).
I've also singned the CLA, the username is ttretter as well.

Cheers, Timo

**Comment by gsmet** [comment]
@ttretter Thanks!

I reworked the commits a bit and merged. It's also backported to the 5.5 branch.

**Comment by ttretter** [comment]
Hi @Sanne 
any chance to get a Bugfix release for that?

**Comment by Sanne** [comment]
@ttretter you're right, sorry I forgot. We'll release it today. Thanks again!

**Comment by Sanne** [comment]
@ttretter version `5.5.6.Final` was released now. Depending on were you are, you might be able to get it via Maven already or you might need some more hours for your favourite mirrors to sync up. Release notes and announcement will appear soon on in.relation.to .

**Comment by ttretter** [comment]
@Sanne Thank you very much!

**Pull request closed without merging**
