### PR TITLE
Component upgrades: Elasticsearch 5.6.2, Gson 2.8.2

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HSEARCH-2892
 - https://hibernate.atlassian.net/browse/HSEARCH-2896

### CODE REVIEW

**Comment by yrodiere** [comment]
@Sanne you need to upgrade the version of Elasticsearch used in tests, too. See the elasticsearch-5.2 profile in the parent pom.

**Comment by Sanne** [comment]
Thanks @yrodiere , commits amended. It still works!

**Comment by yrodiere** [comment]
Merged, thanks!

**Comment by yrodiere** [comment]
Backported to 5.8

**Pull request merged**
