### PR TITLE
HSEARCH-1849 Using Path instead of File in tests to simplify migration

### PR DESCRIPTION
**Pull request by gunnarmorling**
Adapts some test infra to use JDK 7 `Path` instead of `File`. This can be integrated to master, it will simplify migration to Lucene 5 later on.

### CODE REVIEW

**Comment by hferentschik** [comment]
Hmm, seems there is a problem in StoredIndexTest.java:

    [ERROR] /Users/hardy/work/hibernate/git/search/infinispan/src/test/java/org/hibernate/search/infinispan/StoredIndexTest.java:[179,34] unreported exception java.io.IOException; must be caught or declared to be thrown
    [ERROR] /Users/hardy/work/hibernate/git/search/infinispan/src/test/java/org/hibernate/search/infinispan/StoredIndexTest.java:[180,34] unreported exception java.io.IOException; must be caught or declared to be thrown

**Comment by gunnarmorling** [comment]
@hferentschik, oops, pushed an update.

**Comment by Sanne** [comment]
It looks good!
but while I know the relation with Lucene 5 plans (HSEARCH-1849), I'll open a separate issue for this one so that I can merge it in master already without necessarily waiting for the other chunks of work.

**Comment by gunnarmorling** [comment]
Hum, do as you like, but I wouldn't go overboard with micro-JIRAs tbh. Why
can't you merge right now also if HSEARCH-1849 is still open. Or is it you
want to get to HSEARCH-9000 quickly ;)

**Comment by Sanne** [comment]
It's more that I don't want to changes included in a release which are not recorded in the changelog.

We're working on master now which is `5.4`, while the Lucene 5 issue won't be merged until `5.5`.
We could of course wait to merge this, but it doesn't cost me much to open an issue.. what do we have the "trivial" and similar levels for in JIRA otherwise ;)

**Comment by Sanne** [comment]
merged, but as resolving https://hibernate.atlassian.net/browse/HSEARCH-1916

**Pull request closed without merging**
