### PR TITLE
HSEARCH-2570 & HSEARCH-2571 Upgrade maven plugins to support Java 8 code

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-2570
https://hibernate.atlassian.net/browse/HSEARCH-2571

Needed for my implementation of HSEARCH-2561 in particular; the current checkstyle simply rejects any Java 8 constructs.

### CODE REVIEW

**Comment by yrodiere** [comment]
Actually it seems some plugin upgrades are required to support Java 8 code. Investigating.

**Comment by yrodiere** [comment]
@Sanne It works, at last... Here's a proof, a build based on this PR that also adds some lambdas: https://travis-ci.org/yrodiere/hibernate-search/builds/197313903

Please note that I also had to fix HSEARCH-2571, which involves many maven plugin upgrades. I didn't test the release scripts. I'm not sure whether it's possible to run those in an isolated environment... ?

**Comment by yrodiere** [comment]
TODO: when this will be merged, see https://github.com/yrodiere/hibernate-search/commit/a62a9e2e31edbb31f83ee3b893afb43b19659c42#commitcomment-20699212

**Comment by Sanne** [comment]
interesting, building this branch crashes my JVM.. good luck debugging that :D

```

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007f216dd86b84, pid=32512, tid=0x00007f216eaf7700

 JRE version: OpenJDK Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
 Java VM: OpenJDK 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libc.so.6+0x90b84]  __memcpy_sse2_unaligned_erms+0x1a4

 Core dump written. Default location: /home/sanne/workspaces/hibernate/hibernate-search-root/core or core.32512

 An error report file with more information is saved as:
 /home/sanne/workspaces/hibernate/hibernate-search-root/hs_err_pid32512.log

```

**Comment by Sanne** [comment]
regarding the release scripts: yes I'm quite sure something will break there, but since we plan to release a CR and have no strict deadline we can cross fingers.
I think we can in theory test the process, by having Jenkins not push to the repository its changes (nor tags), and then delete the directory from sourceforge. Not sure about the documentation.

I'd say let's just cross fingers.

**Comment by yrodiere** [comment]
@Sanne It doesn't crash mine... I'm using a slightly more recent version of the JDK, though (u101). The newest is u121, by the way.
I'm trying u92 right now. Could you please try the most recent JDK, and if it still fails provide the error report file? Thanks.

**Comment by yrodiere** [comment]
@Sanne Works for me even with 1.8.0_92-b14 with the exact same architecture... Are you able to reproduce it consistently?

**Comment by Sanne** [comment]
"almost consistently": approximately 50% chance it triggered, last night on my workstation.. Switching hardware now to rule out deeper issues.. not that I have much choice, I need to be in the office today, so laptop it is.

**Comment by yrodiere** [comment]
Ok, I'm running the build on 1.8.0_92-b14 in a loop. I'll keep you updated.

**Comment by Sanne** [comment]
whoa, same failure on the laptop. That starts to look like unlikely to be related to hardware issues..

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6d7728b711, pid=11965, tid=0x00007f6d77f42700
#
# JRE version: OpenJDK Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.92-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x14f711]  __memmove_avx_unaligned_erms+0x211
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/sanne/workspaces/hibernate/hibernate-search-root/hs_err_pid11965.log

```

**Comment by yrodiere** [comment]
> whoa, same failure on the laptop.

Still nothing on mine :/
Nothing of interest in `/home/sanne/workspaces/hibernate/hibernate-search-root/hs_err_pid11965.log`?

**Comment by Sanne** [comment]
merged, thanks!

**Pull request closed without merging**
