### PR TITLE
HSEARCH-4021 Revert implicit diamond for JDK 8

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4021

### CODE REVIEW

**Comment by fax4ever** [comment]
I've started a full build to test the JDK8 profile:https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2419/2/pipeline

**Comment by fax4ever** [comment]
Full ci passed, marked +1 to merge it.

**Comment by yrodiere** [comment]
Merged, thanks

**Comment by fax4ever** [comment]
Thank you!

**Pull request merged**
