### PR TITLE
HSEARCH-2188 Fixed type checking in NumericFieldUtilsTest

### PR DESCRIPTION
**Pull request by gfouquet**
`isAssignableFrom` in `NumericFieldUtilsTest` was used the wrong way. I turned it around and added a unit test, which did not pass with the previous implementation.

### CODE REVIEW

**Comment by s4ke** [comment]
What's the difference between this and #1046 ? Please close one.

**Comment by gfouquet** [comment]
There's a patch for branch 5.3 and one for branch 5.4

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
OK, so I pushed the test and the cleanup to master a few weeks ago and backported the original Davide's fix to 5.3 and 5.4 just now.

Closing. Thanks!

**Pull request closed without merging**
