### PR TITLE
HSEARCH-1765 Add support for deleting by Query

### PR DESCRIPTION
**Pull request by s4ke**
https://hibernate.atlassian.net/browse/HSEARCH-1765

I hope I fixed all of the issues stated in the old PR. I will have to rebase this PR after HSEARCH-1795 is merged into master, but this is ready to be reviewed again. The duplicated Commits in here will be removed after hardy's patch is applied as well.

### CODE REVIEW

**Comment by s4ke** [comment]
uhm either Jenkins is broken or something unrelated to my changes just broke.

**Comment by s4ke** [comment]
rebased :)

**Comment by s4ke** [comment]
any updates on this?

**Comment by s4ke** [comment]
rebased :)

**Comment by Sanne** [comment]
I've merged it: looks very good.

Since all commits except the first one were just making corrections to the first one, I've squashed them in a single commit. We don't dislike multiple commits, but only if they help understanding the flow of changes - not needed if they amend mistakes.

I still think the code in `DeleteByQuerySupport` could use a little more polish, but it's not so bad that it should delay having this feature.. so I've opened a separate issue to do that eventually: https://hibernate.atlassian.net/browse/HSEARCH-1841

Thanks! great to have this

**Comment by s4ke** [comment]
thanks for merging :)

**Pull request closed without merging**
