### PR TITLE
Preview of the async backend

### PR DESCRIPTION
**Pull request by s4ke**
I am currently in the progress of merging my GenericJPA project into a submodule of hibernate-search.  As of now I am finished with integrating the async trigger based backend into Hibernate Search ORM.

This pull request is a preview of my work on this part. (The merge is by no means finished, so please don't merge this PR)

### CODE REVIEW

**Comment by s4ke** [comment]
Especially take a look at the orm-async module.

**Comment by s4ke** [comment]
@Sanne did you find the time to take a look at this?

**Comment by s4ke** [comment]
@Sanne bump

**Comment by gunnarmorling** [comment]
Wow, this PR is huge. IIUC, this includes two things: the "async backend" and the "generification". Maybe there is a chance to split these two parts so it gets a bit better manageable?

**Comment by s4ke** [comment]
@gunnarmorling:

sounds reasonable. I will take a look into how I can untangle the two pieces of work as soon as the exam phase at university is over. Also a rebase is probably needed.

**Pull request closed without merging**
