### PR TITLE
HSEARCH-2028

### PR DESCRIPTION
**Pull request by gunnarmorling**
Some doc fixes

### CODE REVIEW

**Comment by Sanne** [comment]
regarding the sorting issue: did you see the user's comment?
https://hibernate.atlassian.net/browse/HSEARCH-2021?focusedCommentId=73504&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-73504

I'm afraid he's right. He can add the fields, but we don't allow the sorting to be defined as it fails validation vs the metadata which we know of.

**Comment by gunnarmorling** [comment]
Ah, didn't see his comment, but I suppose he has a valid point there :/ I think we would allow sorting but would transparently bring in the uninverting reader. Seems there is no easy work-around then (besides of relying on the uninverting reader, but then no field for that reader must be marked as sortable).

**Comment by Sanne** [comment]
I'll push the first commit only, which resolves HSEARCH-2028 nicely. With the second commit you're sneaking in an unrelated task ;-)
Don't delete the commit yet though, it's a nice one for HSEARCH-2021, we just need some more step to figure how it should be done properly.

**Comment by Sanne** [comment]
HSEARCH-2028 is merged; let's repurpose the remaining part?

**Comment by gunnarmorling** [comment]
Going to close this one; I will send the doc update for HSEARCH-2021 as part of #949.

**Pull request closed without merging**
