### PR TITLE
HSEARCH-1984 - Sorting

### PR DESCRIPTION
**Pull request by gunnarmorling**
Still to do:

* ~~Enabling uninverting reader if needed~~
* Still need to recap you discussion on IRC from yesterday

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
It looks good, only minor remarks.
Oh and doc is missing :) And the blog post on it :D

**Comment by Sanne** [comment]
> And the blog post on it :D

right it would be really nice to have a "spot on" blog post rather than having it simply listed as a migration pain during the release announcement.

**Comment by gunnarmorling** [comment]
Added two more commits as per your remarks, @emmanuelbernard, @Sanne.

**Comment by gunnarmorling** [comment]
Added one more commit with ref guide update. Good to go from my side with that.

**Comment by Sanne** [comment]
merged, great!

**Pull request closed without merging**
