### PR TITLE
HSEARCH-4265 Fix flaky tests with MS-SQL and Oracle

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4265

### CODE REVIEW

**Comment by fax4ever** [comment]
Converted to draft, since I want to inspect more on `findOutboxEvents` results, so that we get a meaningful error in case of wrong order instead of having a generic timeout!

**Comment by fax4ever** [comment]
New full build: https://ci.hibernate.org/job/hibernate-search/view/change-requests/job/PR-2622/

**Comment by fax4ever** [comment]
Running the tests again, see https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2622/6/pipeline/66, we don't get the error again.
Anyway, I added a commit to log the returned events in case of wrong error: https://github.com/hiberynate/hibernate-search/pull/2622/commits/4c8a1363482371fec4a57b549cc5e6fa132d8b70.
@yrodiere maybe we should merge it and if the error happens again we will have the log.

**Review by yrodiere — APPROVED** [review]
@fax4ever Are you sure it's not simply a problem with the resolution of the date/time type we're using with MS-SQL? Or the `current_timestamp` function in MS-SQL? That would explain why it only fails from time to time: it fails when the two events are generated too close to each other and are assigned the same timestamp.

Anyway, feel free to merge if that's not the problem.

**Comment by fax4ever** [comment]
Another build with oracle|mssql https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2622/9/pipeline

**Comment by fax4ever** [comment]
Another specific build: https://ci.hibernate.org/job/hibernate-search/view/change-requests/job/PR-2622/11/

**Comment by fax4ever** [comment]
Merged, thanks!

**Pull request merged**
