### PR TITLE
HSEARCH-2858 Using @ContainedIn in a @Spatial-annotated entity triggers a NullPointerException on startup

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-2858

To be backported to 5.6 and 5.7. Maybe even 5.5, but I didn't try that one.

### CODE REVIEW

**Comment by Sanne** [comment]
checkstyle is unhappy ;)

**Comment by yrodiere** [comment]
> checkstyle is unhappy ;)

Fixed, sorry about that.

**Comment by Sanne** [comment]
The fix looks reasonable but I'm not seeing the relation with the test?

I tried to run the test after reverting the fix and indeed it's still passing.

**Comment by yrodiere** [comment]
@Sanne I tried to simplify the test too hard... Will correct that.

**Comment by yrodiere** [comment]
@Sanne Should be okay now... The test fails without the fix, succeeds with the fix, checkstyle passes, and I added a few comments in the test to explain what's going on. Let's wait for the CI just in case...

**Comment by Sanne** [comment]
thanks, understand it now and it works! merged

**Pull request merged**
