### PR TITLE
HSEARCH-1780 Update link to Luke in docs

### PR DESCRIPTION
**Pull request by DavideD**
https://hibernate.atlassian.net/browse/HSEARCH-1780

### CODE REVIEW

**Comment by Sanne** [comment]
So what is the reason. The version on google code isn't compatible anymore, but you had success with that fork?

**Comment by DavideD** [comment]
Yes, that fork worked for me while the  version on google code didnt

**Comment by Sanne** [comment]
thanks, merged!

**Comment by hferentschik** [comment]
The Google code sources are outdated. When I was looking for a Luke version for my DocValues stuff, I had to find a working version. Apparently, there is no blessed fork, but the one we picked seems most up to date.

**Pull request closed without merging**
