### PR TITLE
HSEARCH-4265 Make sure events are outdistanced

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4265

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
LGTM. Feel free to merge when it passes.

For future reference: https://hibernate.zulipchat.com/#narrow/stream/132092-hibernate-search-dev/topic/HSEARCH-4265/near/247308063

**Comment by fax4ever** [comment]
Here is a full-build: https://ci.hibernate.org/job/hibernate-search/view/change-requests/job/PR-2624/2

**Comment by fax4ever** [comment]
Thanks for the review. I'll merger as soon as it passes!

**Comment by fax4ever** [comment]
Merged, thanks!

**Pull request merged**
