### PR TITLE
HSEARCH-3267 Restore option to run WildFly integration tests against manually prepared distribution

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-3267

### CODE REVIEW

**Comment by yrodiere** [comment]
Tested locally with:

* Two instances of WF 14 Beta (more precisely, EAP 7.2.0-CD14)
* `mvn clean install -DskipTests`
* `mvn clean verify -pl integrationtest/wildfly -DjbossHome.node1=path-to-node1 -DjbossHome.node2=path-to-node2 -DbuiltinVersion=5.10.3.Final`

It worked, and the target directory did not contain any automatically provisioned WF instance, so the tests actually ran against the external WF instance.

**Comment by yrodiere** [comment]
@simkam Could you please confirm this makes the trick for you, either by testing this branch or by testing the [backport to 5.10](https://github.com/hibernate/hibernate-search/pull/1722)?

**Comment by simkam** [comment]
@yrodiere both, this and backport, work for me. Thanks a lot!

**Comment by yrodiere** [comment]
Merging, thanks!

**Pull request merged**
