### PR TITLE
HSEARCH-1922 Using standard JMS header JMSXGroupID for Environment.IN…

### PR DESCRIPTION
**Pull request by hferentschik**
…DEX_NAME_JMS_PROPERTY

Small change which will allow for a true HA JMS master/slave setup.

### CODE REVIEW

**Comment by Sanne** [comment]
Do you think it has any backwards compatibility impact?

I'm thinking about the case in which one upgrades the master, but still has pending messages in the queue (previously persisted, or still being produced).
These messages will have the index name encoded in a different property, and fail.

We could simply encode both for a transitionally time, and have the master code try read the new one as first option but fallback to the deprecated name?

**Comment by hferentschik** [comment]
> I'm thinking about the case in which one upgrades the master, but still has pending messages in the queue (previously persisted, or still being produced).
These messages will have the index name encoded in a different property, and fail.

True, that would be a problem. But do we even support such a incremental upgrade. Also I expect that for our scenario the queue is not storing messages for a long time. The whole idea is to process them directly. Also, we are talking about a Lucene upgrade for the next version. If you ask me, I would stay away from any such incremental upgrade attempts. 

> We could simply encode both for a transitionally time, and have the master code try read the new one as first option but fallback to the deprecated name?

Sure, but that's again more code for imo minimal benefit.

**Comment by Sanne** [comment]
I added two lines to fallback to the old property name, but I agree with you on not spending much more on it so I'll not add explicit upgrading tests nor bother you with an additional PR.. integrating!

**Comment by hferentschik** [comment]
Fair enough.

**Pull request closed without merging**
