### PR TITLE
Resolving the timeout exceptions we've seen on CI

### PR DESCRIPTION
**Pull request by Sanne**
See also JIRA description for the explanation:
 - https://hibernate.atlassian.net/browse/HSEARCH-2681

### CODE REVIEW

**Comment by Sanne** [comment]
retest this please

**Comment by Sanne** [comment]
@Hibernate-CI test this please

**Comment by yrodiere** [comment]
@Sanne About the failure we had soone, related to a malformed HTTP responser: I created a JIRA. https://hibernate.atlassian.net/browse/HSEARCH-2682

**Comment by yrodiere** [comment]
Jenkins, retest this please

**Comment by yrodiere** [comment]
Merged. Thanks!

**Comment by atulsudhalkar** [comment]
Did this fix make into any recent ES releases? I'm running into the same exception, but I'm on ES 6.2!

**Comment by yrodiere** [comment]
@atulsudhalkar Here is the issue on the Elasticsearch bugtracker: https://github.com/elastic/elasticsearch/issues/24069

It seems a fix was merged on March 28.

I don't know about Elasticsearch 6.2, since Hibernate Search currently only support 5.x, but on 5.6 at least the workaround added in this PR works just fine.

**Comment by Sanne** [comment]
It was eventually resolved via https://github.com/elastic/elasticsearch/pull/30384

So Elasticsearch I expect it fixed in versions 6.3.1, 6.4.0, 7.

**Comment by atulsudhalkar** [comment]
Hi Sanne,

Thank you so much for the response! Appreciate it greatly!

--atul

**Pull request merged**
