### PR TITLE
HSEARCH-2367 LuceneQueryDescriptor ignores targetEntities

### PR DESCRIPTION
**Pull request by gustavonalle**
https://hibernate.atlassian.net/browse/HSEARCH-2367

### CODE REVIEW

**Comment by yrodiere** [comment]
@gustavonalle Thanks for your report and PR. I answered on the JIRA ticket with a possible solution to your issue, and I'm going to investigate to try to fix this and other issues at the same time.

**Comment by Sanne** [comment]
N.B. `org.hibernate.search.elasticsearch.impl.ElasticsearchJsonQueryDescriptor` also ignores the types. We can discuss improving the approach but let's keep the two consistent?

**Comment by yrodiere** [comment]
I opened PR containing an alternative solution: #1172
That one does address the `ElasticsearchJsonQueryDescriptor` issue too, but requires some SPI changes.
I'm keeping this PR opened for now, since I'm not sure #1172 will make it to master.

**Comment by yrodiere** [comment]
Fixed in #1172 ; closing this PR. Thanks for pointing out the issue!

**Comment by gustavonalle** [comment]
cool, thanks for the quick fix!

**Pull request closed without merging**
