### PR TITLE
HSEARCH-3560 Elasticsearch AWS should support AWS Credential Providers for authentication

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-3560

### CODE REVIEW

**Comment by yrodiere** [comment]
Full build: https://ci.hibernate.org/job/hibernate-search/job/PR-2378/2/

**Comment by yrodiere** [comment]
Looks like one particular test is failing when using session tokens for AWS authentication... I'm having a look.

**Comment by yrodiere** [comment]
I think the session credentials expired after 1 hours, and some requests started failing when it was time to renew the credentials. No sure why the AWS SDK didn't renew the credentials before they expired, but that's a question for another day.

Started another build: https://ci.hibernate.org/job/hibernate-search/job/PR-2378/3/

**Comment by fax4ever** [comment]
Very good job. Merged, thanks!

**Pull request merged**
