### PR TITLE
HSEARCH-2607 Improve OSGi test diagnostics when running tests on misc…

### PR DESCRIPTION
**Pull request by Sanne**
…onfigured networks

https://hibernate.atlassian.net/browse/HSEARCH-2607

### CODE REVIEW

**Comment by Sanne** [comment]
Ok, interesting.

I've sent a PR to the CI configuration to improve its configuration:
 - https://github.com/hibernate/ci.hibernate.org/pull/42

Let's hope Travis is having a better default?

**Comment by yrodiere** [comment]
@Sanne I launched a job for your commit on travis, we'll see: https://travis-ci.org/yrodiere/hibernate-search/builds/206522400

**Comment by yrodiere** [comment]
Unfortunately it doesn't work on Travis, either:

```
testLocalhostResolution(org.hibernate.search.test.integration.osgi.SystemTest)  Time elapsed: 0.014 sec  <<< FAILURE!
org.junit.ComparisonFailure: local machine name 'testing-gce-89719e7d-96d7-4b32-8350-d68cc17fa7d3' does not resolve to '127.0.0.1'. Fix your network configuration to be able to run the OSGi integration tests. expected:<127.0.[0].1> but was:<127.0.[1].1>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.hibernate.search.test.integration.osgi.SystemTest.testLocalhostResolution(SystemTest.java:28)
```

**Comment by Sanne** [comment]
thanks. That suggests they are using a quite old version of Debian :(
I'll find an alternative way to check for "sanity" which isn't this strict.

**Pull request closed without merging**
