### PR TITLE
HSEARCH-2139

### PR DESCRIPTION
**Pull request by gunnarmorling**
Supersedes #1021.

### CODE REVIEW

**Comment by gsmet** [comment]
Looks good to me.

**Comment by Sanne** [comment]
@gsmet may I assume you'll rebase and push it?

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks for checking, everyone!

**Comment by Sanne** [comment]
I'm resolving the JIRA.. I guess that was just being forgotten, if not and you think something else is needed please open a follow up.

**Pull request closed without merging**
