### PR TITLE
HSEARCH-3846 Filtering multi values for sort and aggregation

### PR DESCRIPTION
**Pull request by wklaczynski**
https://hibernate.atlassian.net/browse/HSEARCH-3846

Fixing the problem of aggregating multiple HSEARCH-3846 values. Added filtering of nested filter minister values for sorting and aggregation. A solution for sorting multiple values in user provided mode.

### CODE REVIEW

**Comment by wklaczynski** [comment]
I think the last commit solves the problem of multiple values. In the future, you can try to scan queries to extract questions for aggregation or sorting filters. But now you can easily sort and aggregate queries, so the goal is achieved. All code can be used for closing.

**Comment by yrodiere** [comment]
Multi-valued sorts have just been merged into master, but with a few changes. Could you please:

* Rebase your work on the `master` branch. See https://help.github.com/en/github/using-git/about-git-rebase#rebasing-commits-against-a-branch
* Format your commits according to the project's conventions explained in [CONTRIBUTING.md](https://github.com/hibernate/hibernate-search/blob/master/CONTRIBUTING.md), in particular prefixing every commit message with the ticket number. E.g. `HSEARCH-3846 Function optimization and fix tests`.
* Make sure the CI build passes.

**Comment by wklaczynski** [comment]
I will do rebase to the current master. But I think it's better if I create a new branch. It will be easier.

**Comment by yrodiere** [comment]
Alright, thanks. Closing this, then.

**Pull request closed without merging**
