### PR TITLE
HSEARCH-668 Transactional JMS

### PR DESCRIPTION
**Pull request by DavideD**
I've added a few commits to @emmanuelbernard  pull request: https://github.com/hibernate/hibernate-search/pull/858

I think now it's good to go.

### CODE REVIEW

**Comment by DavideD** [comment]
@emmanuelbernard I've removed the commit with the refactoring

**Comment by Sanne** [comment]
@DavideD were you not to add a test using projections?

**Comment by DavideD** [comment]
@Sanne I've added the assertion in the existing test. We can split it in two separate tests if you prefer

**Comment by Sanne** [comment]
It's failing the tests: searchRollbackedMemberAfterSynchronizationOnSlave2

The method is waiting a bit but the overall wait time is lower than REFRESH_PERIOD_IN_SEC

**Comment by Sanne** [comment]
I was wrong on the wait time, still the test is failing.

**Comment by Sanne** [comment]
status update: I'm debugging and adding some diagnostic logging

**Comment by Sanne** [comment]
this was updated and merged

**Pull request closed without merging**
