### PR TITLE
HSEARCH-2512 Force OSGi integration tests to use the loopback device …

### PR DESCRIPTION
**Pull request by Sanne**
…for RMI

https://hibernate.atlassian.net/browse/HSEARCH-2512

### CODE REVIEW

**Comment by yrodiere** [comment]
Jenkins, test this please

**Comment by Sanne** [comment]
what was wrong here, is CI refusing to run it?

**Comment by yrodiere** [comment]
@Sanne No, a performance test failed. This happens randomly sometimes :/

**Comment by yrodiere** [comment]
Looks good to me. Merged, thanks!

**Pull request merged**
