### PR TITLE
Reviewing IndexControlMBean and modernising statistics generation

### PR DESCRIPTION
**Pull request by Sanne**
Two simple and relaxing ones..

I added HSEARCH-2763 as the first one was way too simple.

 - https://hibernate.atlassian.net/browse/HSEARCH-2666
 - https://hibernate.atlassian.net/browse/HSEARCH-2763

### CODE REVIEW

**Comment by yrodiere** [comment]
Any reason why we shouldn't use `LongAdder` in `org.hibernate.search.test.integration.osgi.HibernateSearchWithKarafIT.AssertingMassIndexerProgressMonitor`? It seems the `addAndGet` & co are unnecessary there.

Also, there's a typo in the last commit message ("HSEARCH-2763 Last minor opportunity to conver to a LongAdder"); just mentioning this so I remember to fix it when merging.

**Comment by yrodiere** [comment]
> Any reason why we shouldn't use `LongAdder` in `org.hibernate.search.test.integration.osgi.HibernateSearchWithKarafIT.AssertingMassIndexerProgressMonitor`? It seems the `addAndGet` & co are unnecessary there.
> 
> Also, there's a typo in the last commit message ("HSEARCH-2763 Last minor opportunity to conver to a LongAdder"); just mentioning this so I remember to fix it when merging.

Also, the documentation should be updated (`monitoring.asciidoc`):

==== IndexControlMBean

> This MBean allows to build, optimize and purge the index for a given entity. Indexing occurs via the
> mass indexing API (see <<search-batchindex-massindexer>>). A requirement for this bean to be
> registered in JMX is, that the Hibernate SessionFactory is bound to JNDI via the
> `hibernate.session_factory_name` property. Refer to the Hibernate Core manual for more
> information on how to configure JNDI. **The IndexControlMBean and its API are for now experimental.**

**Comment by Sanne** [comment]
thanks for spotting those! Will amend shortly

**Comment by Sanne** [comment]
updated

**Comment by yrodiere** [comment]
Merged!

**Pull request merged**
