### PR TITLE
Elasticsearch followup v2

### PR DESCRIPTION
**Pull request by Sanne**
Follow up @gunnarmorling 's PR #960 : rebased and fixed some tests.
Also had to disable some more tests which I couldn't fix.

N.B. the correct spelling for "Elasticsearch" is NOT "ElasticSearch" .. renamed classes, comments and logged messages.
Hopefully we're still early enough to limit the damage of renaming files with different case ;-)

### CODE REVIEW

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-search/pull/980

**Comment by gunnarmorling** [comment]
Jippie :)

**Comment by Sanne** [comment]
nice! :+1:

**Comment by gunnarmorling** [comment]
Hey @gsmet, now with this puppy in, can you rebase your faceting work on upstream/master? I'll work on some improvements around nested elements ("index embedded") next. Maybe you can send in a PR for your faceting work?

**Comment by gsmet** [comment]
Working on it.

It's even funnier with all the renaming!

**Comment by gsmet** [comment]
Done! https://github.com/hibernate/hibernate-search/pull/981

**Pull request merged**
