### PR TITLE
HSEARCH-4826 Remove unused Maven plugins from the POM

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HSEARCH-4826

- release/site/help plugins removed
- replaced io.takari.maven plugin with the one from maven itself since this one is already in an "archived state". regenerated the wrapper using a new plugin (https://maven.apache.org/wrapper/maven-wrapper-plugin/wrapper-mojo.html)
- also looks like groovy engine is moved to apache group - so replaced it as well.

As for the other plugins. Questionable: 

**dependency-check-maven - _cannot see it being used, hidden somewhere? Didn't remove it as it seems ok to actually run it._**
**lifecycle-mapping - _eclipse (not used :))_**
**maven-deploy-plugin - _we keep it so we can ignore it as we are using a nexus-staging-maven-plugin instead?_**

Used:
maven-wrapper-plugin - not really used unless we want to manually regenerate mvnw
jdeps-maven-plugin - to call manually
maven-clean-plugin - well :)
maven-install-plugin - same :) two favourite plugins :)
maven-resources-plugin - copy various themes, styles etc
maven-jar-plugin - not as cool as clean/install but used :)
maven-compiler-plugin - :)
maven-processor-plugin - create benchmarks 
nexus-staging-maven-plugin - for release
maven-assembly-plugin - to build dist artefacts
maven-javadoc-plugin - :)
maven-source-plugin - used
maven-dependency-plugin - for javadocs download and other deps to unpack
maven-enforcer-plugin - used to enforce various lib/java versions + dependency convergence
exec-maven-plugin - various print-versions + for collecting config properties
maven-bundle-plugin - used to update manifest
maven-shade-plugin - used to modify jars (property collector, benchmarks)
build-helper-maven-plugin - get versions, add sources ...
versions-maven-plugin - used in upgrade jobs
forbiddenapis - YES! :)
maven-checkstyle-plugin - used
moditect-maven-plugin - used
maven-injection-plugin - used to set lib version into org.hibernate.search.engine.Version
jandex-maven-plugin - used to generate an index for tests
maven-surefire-plugin - used
maven-failsafe-plugin - used
docker-maven-plugin - used
avro-maven-plugin - for orm-coordination-outbox-polling DTOs
jacoco-maven-plugin - used
asciidoctor-maven-plugin - used
sonar-maven-plugin - used (for CI)
maven-scripting-plugin - used (for CI) list containers to pull
maven-gpg-plugin - sign artefacts for the release
maven-antrun-plugin - all jakarta/orm6 code transformations
maven-project-info-reports-plugin -  is this one for CI builds?
japicmp-maven-plugin - used
jqassistant-maven-plugin - used

### CODE REVIEW

**Comment by yrodiere** [comment]
> lifecycle-mapping - eclipse (not used :))

Well last time I checked it was necessary to import the project into Eclipse... If you're removing it, you'll have to check that it's no longer necessary in Eclipse.

> maven-deploy-plugin - we keep it so we can ignore it as we are using a nexus-staging-maven-plugin instead?

I think that's the spirit, yes.

If removing version management does not lead to warnings, feel free to do so.

> dependency-check-maven - cannot see it being used, hidden somewhere? Didn't remove it as it seems ok to actually run it.
> jdeps-maven-plugin - to call manually
> maven-project-info-reports-plugin - is this one for CI builds?
> japicmp-maven-plugin - used

Not sure about these... I think it's used by people productizing Hibernate Search at Red Hat, but I'll need to check.

**Comment by marko-bekhta** [comment]
>Well last time I checked it was necessary to import the project into Eclipse... If you're removing it, you'll have to check that it's no longer necessary in Eclipse.

I think it still is, it was more of a joke, that we aren't importing into Eclipse 🙈 😃

**Comment by yrodiere** [comment]
Right, it's more for the benefit of external contributors who would want to use Eclipse. We even have a dedicated CI job to ensure Eclipse's compiler is happy with our code (it does not always behave like javac...), also for the benefit of external contributors.

**Review by yrodiere — APPROVED** [review]
Alright let's merge as-is -- it's a great step forward already.

We'll see about removing those at some point... someday:



```
    dependency-check-maven - cannot see it being used, hidden somewhere? Didn't remove it as it seems ok to actually run it.
    jdeps-maven-plugin - to call manually
    maven-project-info-reports-plugin - is this one for CI builds?
    japicmp-maven-plugin - used
```

**Pull request merged**
