### PR TITLE
HSEARCH-2083 Upgrade to Apache Lucene 5.4.1

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HSEARCH-2083

### CODE REVIEW

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-search/pull/975

**Comment by gunnarmorling** [comment]
WildFly 10.0 still is on 5.3.1, I hope that's no problem for integration
testing, or usage on WF in more general terms?

2016-02-01 10:01 GMT+01:00 DavideD <notifications@github.com>:

**Comment by DavideD** [comment]
@gunnarmorling 
Search refers to its own lucene module with slot  5.4 created during the build

**Comment by gunnarmorling** [comment]
Ah sweet, that's perfect!

**Pull request closed without merging**
