### PR TITLE
HSEARCH-4740 Run tests against Elasticsearch 7.17.8

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-4740

[HSEARCH-4740]: https://hibernate.atlassian.net/browse/HSEARCH-4740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by yrodiere** [comment]
Looks like Elasticsearch 7.17.7 is affected by https://github.com/elastic/elasticsearch/issues/84601... and also another bug that I had to work around in #3296... I'll have to think a bit and see what my options are.

**Comment by yrodiere** [comment]
> Looks like Elasticsearch 7.17.7 is affected by [elastic/elasticsearch#84601](https://github.com/elastic/elasticsearch/issues/84601)... and also another bug that I had to work around in #3296... I'll have to think a bit and see what my options are.

7.17.8 is still affected.

**Comment by yrodiere** [comment]
I disabled some tests on Elasticsearch 7.17.7+, since that's about all we can do at this point. Let's see how it goes.

**Review by marko-bekhta — APPROVED** [review]

**Comment by yrodiere** [comment]
It worked, merging.

**Pull request merged**
