### PR TITLE
Restore support for full-text filters HSEARCH-3325

### PR DESCRIPTION
**Pull request by wklaczynski**
Restore support for full-text filters

```java
@FullTextFilter(name = "is-active", factory = @FilterFactoryRef(type = PricesActiveFilterFactory.class))
@FullTextFilter(name = "is-shared", factory = @FilterFactoryRef(type = PermissionsFilterFactory.class), params = {
    @FilterParam(name = "operation", value = "share"),
    @FilterParam(name = "field", value = "sharings")
})
@Entity(name = "AssortmentPrice")
public class AssortmentPrice implements Serializable {
```

### CODE REVIEW

**Comment by yrodiere** [comment]
As I said on the ticket, this does not just restore the full-text filters feature, but adds new concepts (passing a field path through the filter reference) and remove some others (caching, applying a filter after the query was built). The value of filters as you propose to expose them is also unclear, since users can achieve similar results with just as much code and without filters.

Let's continue the discussion on https://hibernate.atlassian.net/browse/HSEARCH-3325 . If we identify a clear improvement brought by this PR, we may consider merging it.

**Comment by wklaczynski** [comment]
This is the entire use case, which, among other things, problems a patch solves. Thanks to this, present, I've managed to hide the entire implementation of permissions under one annotation.

```java
public class PermissionsBinder implements TypeBinder {

    private String fieldName = "permissions";
    private String operationName = "read";
    private String filterName = "has-permission";

    public PermissionsBinder fieldName(String fieldName) {
        this.fieldName = fieldName;
        return this;
    }

    public PermissionsBinder operationName(String operationName) {
        this.operationName = operationName;
        return this;
    }

    public PermissionsBinder filterName(String filterName) {
        this.filterName = filterName;
        return this;
    }

    @Override
    public void bind(TypeBindingContext context) {
        context.getDependencies().useRootOnly();

        IndexFieldReference<String> permissionsField = context.getIndexSchemaElement()
                .field(this.fieldName, f -> f.asString()
                .aggregable(Aggregable.NO)
                .sortable(Sortable.NO)
                .searchable(Searchable.YES)
                .analyzer("permissions"))
                .toReference();

        context.getIndexSchemaElement().filter(this.filterName, new Filter())
                .param("operation", operationName)
                .param("field", this.fieldName)
                .toReference();

        context.setBridge(new Bridge(
                permissionsField
        ));
    }

    private static class Bridge implements TypeBridge {

        private final IndexFieldReference<String> permissionsField;

        protected IdentityStoreResolver getIdentityService() {
            IdentityStoreResolver isr = ServiceLocator.getService(IdentityStoreResolver.class, IdentityStoreResolver.JNDI_NAME);
            return isr;
        }

        private Bridge(IndexFieldReference<String> permissionsField) {
            this.permissionsField = permissionsField;
        }

        @Override
        public void write(DocumentElement target, Object bridgedElement, TypeBridgeWriteContext context) {
            StringBuilder brules = new StringBuilder();

            IdentityStoreResolver isr = getIdentityService();
            PermissionManager pm = isr.getPermissionManager();

            List<Permission> permissions = pm.listPermissions(bridgedElement);
            for (Permission permission : permissions) {
                IdentityType assignee = permission.getAssignee();

                if (assignee instanceof Group) {
                    String[] roles = permission.getRoles();
                    if (roles == null || roles.length < 1) {
                        roles = new String[]{"*"};
                    }
                    for (String role : roles) {
                        brules.append(permission.isAllow() ? "+" : "-");
                        brules.append(permission.getOperation()).append(":");
                        brules.append(permission.getContext()).append(":");
                        brules.append(role).append(":");
                        brules.append(permission.getPath());
                        brules.append("\n");
                    }
                } else {
                    brules.append(permission.isAllow() ? "+" : "-");
                    brules.append(permission.getOperation()).append(":");
                    brules.append(permission.getContext()).append(":");
                    brules.append("*").append(":");
                    brules.append(permission.getPath());
                    brules.append("\n");
                }
            }

            String rules = brules.toString();
            target.addValue(this.permissionsField, rules);
        }
    }

    private static class Filter implements FilterFactory {

        @Override
        public SearchPredicate create(FilterFactoryContext ctx) {
            SearchPredicate filter;
            Account user = ctx.param("user");
            String fieldPath = ctx.resolvePath(ctx.param("field"));
            String operation = ctx.param("operation");

            if (operation == null) {
                operation = "read";
            }

            SearchPredicateFactory predicate = ctx.predicate();

            PermissionQuery allowQuery = new PermissionQuery(fieldPath, operation, user, true);
            PermissionQuery dannyQuery = new PermissionQuery(fieldPath, operation, user, false);

            BooleanQuery query = new BooleanQuery.Builder()
                    .add(allowQuery, BooleanClause.Occur.MUST)
                    .add(dannyQuery, BooleanClause.Occur.MUST_NOT)
                    .build();

            filter = predicate
                    .extension(LuceneExtension.get())
                    .fromLuceneQuery(query)
                    .toPredicate();

            String nestedPath = ctx.getNestedPath();
            if (nestedPath != null) {
                filter = predicate.nested().objectField(nestedPath)
                        .nest(filter).toPredicate();
            }

            return filter;
        }

    }

}
```
```java
public class PermissionQuery extends MultiTermQuery {

    private final String operation;

    private final Account user;
    private final boolean allow;
    private final String prefix;
    private final PermissionResolver pr;

    public PermissionQuery(String field, String operation, Account user, boolean allow) {
        super(field);
        this.operation = operation;
        this.user = user;
        this.allow = allow;

        IdentityStoreResolver isr = ServiceLocator.getService(IdentityStoreResolver.class, IdentityStoreResolver.JNDI_NAME);
        pr = isr.getPermissionResolver();
        prefix = (allow ? "+" : "-") + operation + ":";
    }

    @Override
    protected TermsEnum getTermsEnum(Terms terms, AttributeSource atts) throws IOException {
        TermsEnum tenum = terms.iterator();
        if (user == null) {
            return tenum;
        }
        return new PermissionTermsEnum(tenum, user);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.field);
        hash = 79 * hash + Objects.hashCode(this.operation);
        hash = 79 * hash + Objects.hashCode(this.user);
        hash = 79 * hash + (this.allow ? 1 : 0);
        hash = 79 * hash + Objects.hashCode(this.prefix);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PermissionQuery other = (PermissionQuery) obj;
        if (!Objects.equals(this.field, other.field)) {
            return false;
        }
        if (this.allow != other.allow) {
            return false;
        }
        if (!Objects.equals(this.operation, other.operation)) {
            return false;
        }
        if (!Objects.equals(this.prefix, other.prefix)) {
            return false;
        }
        return Objects.equals(this.user, other.user);
    }

    @Override
    public String toString(String field) {
        StringBuilder buffer = new StringBuilder();
        if (!field.equals(field)) {
            buffer.append(field);
            buffer.append(":");
        }
        buffer.append('/');
        buffer.append(user.toString());
        return buffer.toString();
    }

    public final class PermissionTermsEnum extends FilteredTermsEnum {

        public PermissionTermsEnum(TermsEnum tenum, Account user) {
            super(tenum);
            setInitialSeekTerm(new BytesRef(""));
        }

        @Override
        protected BytesRef nextSeekTerm(BytesRef currentTerm) throws IOException {
            if (currentTerm == null) {
                return super.nextSeekTerm(currentTerm);
            } else {
                return tenum.next();
            }
        }

        @Override
        protected FilteredTermsEnum.AcceptStatus accept(BytesRef term) throws IOException {
            String rule = term.utf8ToString();
            boolean accept = false;

            if (allow && rule.startsWith(prefix)) {
                accept = true;
                System.out.println(rule);
                rule = rule.substring(prefix.length());
            }

            if (!allow && rule.startsWith(prefix)) {
                accept = true;
                System.out.println(rule);
                rule = rule.substring(prefix.length());
            }

            if (accept) {
                accept = pr.resolvePermission(user, rule);
            }

            return accept ? FilteredTermsEnum.AcceptStatus.YES_AND_SEEK : FilteredTermsEnum.AcceptStatus.NO_AND_SEEK;
        }

    }

}
```

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
@TypeMapping(processor = @TypeMappingAnnotationProcessorRef(
        type = PermissionsBinding.Processor.class
))
@Documented
public @interface PermissionsBinding {

    String fieldName() default "permissions";
    String defaultOperation() default "read";
    String filterName() default "has-permission";

    class Processor implements TypeMappingAnnotationProcessor<PermissionsBinding> {

        @Override
        public void process(TypeMappingStep mapping, PermissionsBinding annotation,
                TypeMappingAnnotationProcessorContext context) {

            PermissionsBinder binder = new PermissionsBinder();

            if (!annotation.fieldName().isEmpty()) {
                binder.fieldName(annotation.fieldName());
            }
            if (!annotation.defaultOperation().isEmpty()) {
                binder.operationName(annotation.defaultOperation());
            }
            if (!annotation.filterName().isEmpty()) {
                binder.filterName(annotation.filterName());
            }
            mapping.binder(binder);
        }
    }

}
```

```java
public class PricesActiveFilterFactory implements FilterFactory {

    @Override
    public SearchPredicate create(FilterFactoryContext ctx) {
        SearchPredicate filter;
        String fieldPath = ctx.resolvePath("active");

        filter = ctx.predicate()
                .match().field(fieldPath)
                .matching(true)
                .toPredicate();

        return filter;
    }

}
```

Access to the whole in every other entity through.

```java
@Entity(name = "AssortmentPrice")
@FullTextFilter(name = "is-active", factory = @FilterFactoryRef(type = PricesActiveFilterFactory.class))
@PermissionsBinding(defaultOperation = "share")
public class AssortmentPrice implements Serializable {
...
   @GenericField
    @Column(name = "Active")
    private boolean active = true;
...
}
```

```java
@Entity(name = "Assortment")
@Table(
        name = "Assortment",
        indexes = {
            @Index(columnList = "name")
        }
)
@Inheritance(strategy = InheritanceType.JOINED)
public class Assortment implements Serializable {
...
    @IndexedEmbedded(storage = ObjectFieldStorage.NESTED)
    @OneToMany(mappedBy = "assortment", orphanRemoval = true, fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    private List<AssortmentPrice> prices = new ArrayList<>();
...
}
```

Here's the query in LazyDataModel from the primefaces table.

```java
    private class BeansDataModel extends SearchDataModel<Assortment> {

        @Override
        public SearchQuery<Assortment> search(Map<String, SortMeta> sortBy, Map<String, FilterMeta> filterBy) {

            try {
                SearchSession session = Search.session(em);
                SearchScope<Assortment> scope = session.scope(Assortment.class);

                SearchSortFactory sorter = scope.sort();
                CompositeSortComponentsStep sort = sorter.composite();

                SearchPredicateFactory spf = scope.predicate();

                BooleanPredicateClausesStep pricesFilter = spf.bool()
                        .filter(spf.def("prices.is-active"))
                        .filter(spf.def("prices.has-permission")
                                .param("operation", "share")
                                .param("user", identity.getAccount())
                        );

                sort.add(sorter.field("prices.bruttoPrice_sort")
                        .asc()
                        .mode(SortMode.MIN)
                        .filter(pricesFilter));

                for (String key : sortBy.keySet()) {
                    SortMeta sortMeta = sortBy.get(key);
                    String fieldName = sortMeta.getSortField();
                    switch (sortMeta.getSortOrder()) {
                        case ASCENDING:
                            sort.add(sorter.field(fieldName).asc());
                            break;
                        case DESCENDING:
                            sort.add(sorter.field(fieldName).desc());
                            break;
                    }
                }

                PredicateFinalStep select;
                if (searchFullText != null) {
                    select = scope.predicate().simpleQueryString()
                            .field("shoppingName").boost(0.5f)
                            .matching(searchFullText);
                } else {
                    select = scope.predicate()
                            .matchAll();
                }

                SearchQuery<Assortment> query = session.search(scope)
                        .where((f) -> f.bool().must(select)
                        .filter(pricesFilter))
                        .sort(sort.toSort())
                        .toQuery();

                return query;
            } catch (Exception ex) {
                throw new IllegalStateException(ex);
            }
        }
    }
```

This greatly simplifies the closed complicated problem. Ultimately, a simple solution is visible.

**Comment by wklaczynski** [comment]
I pulled out all the changes to the current master version with aggregation sorting. In line with the changes, I used similar solutions for dsl context that were for sorting.

**Comment by yrodiere** [comment]
Since it's been a while, this code would require extensive changes before it can be merge. And there is, of course, still the problem of identifying what this brings compared to alternative solutions.
I'm going to close this; let's continue the discussion on https://hibernate.atlassian.net/browse/HSEARCH-3325 if necessary.

**Pull request closed without merging**
