### PR TITLE
HSEARCH-2453 Add unit tests for JestClient (authentication in particular)

### PR DESCRIPTION
**Pull request by yrodiere**
Follow-up on #1309 : https://hibernate.atlassian.net/browse/HSEARCH-2453

Here are the test you asked for, @Sanne ;)
We can also backport this if you think it's worth it.

### CODE REVIEW

**Comment by yrodiere** [comment]
I just force-pushed an update to solve a dependency convergence issue. Hope this will fix the build...

**Comment by Sanne** [comment]
looks great! Thanks for researching this, feels much better.

Testing now..

**Comment by Sanne** [comment]
there's some problem with the dependencies, I guess caused by the exclusions you had to add.

```
Tests in error: 
  JestClientTest.authentication:163 » NoClassDefFound com/fasterxml/jackson/data...
  JestClientTest.multipleHosts:122 » NoClassDefFound com/fasterxml/jackson/datab...
  JestClientTest.simple:69 » NoClassDefFound com/fasterxml/jackson/databind/Json...

```

**Comment by yrodiere** [comment]
@Sanne Solved, sorry about that.
So in the end, there were two issues:

 * a dependency convergence between wiremock and jest
 * a dependency convergence within jackson itself (jackson-databind 2.6.1 depends on jackson-annotations 2.6.0, go figure...), which wiremock depends on

**Comment by Sanne** [comment]
merged! thanks. I'll backport as well.

**Pull request closed without merging**
