### PR TITLE
HSEARCH-2529 Avoid NPE when logging errors on Lucene works with no related entity

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-2529

### CODE REVIEW

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by yrodiere** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request merged**
