### PR TITLE
Reduce test verbosity and warnings

### PR DESCRIPTION
**Pull request by Sanne**
This also improves build execution times a bit.

 - https://hibernate.atlassian.net/browse/HSEARCH-2694

### CODE REVIEW

**Comment by yrodiere** [comment]
@Sanne Don't you want to do the same for ES2? As it's an embedded instance, it uses the same configuration as the rest of our tests, though. Maybe the configuration for ES2 should be in `sharedtestresources/src/main/resources/log4j.properties`?

**Comment by Sanne** [comment]
@yrodiere no I'm not too interested in spending time polishing the ES2 tests :)

Speaking of resources, I actually think they shouldn't be in `src/[test|main]/resources` at all as we don't load them from our testsuite.
In fact I had them in the root before, but you moved them in the resources. Having them in `sharedtestresources` seems interesting but that's a task for another day.. not sure if the ES plugin can deal with that.

**Comment by yrodiere** [comment]
> Speaking of resources, I actually think they shouldn't be in src/[test|main]/resources at all as we don't load them from our testsuite.

Created https://hibernate.atlassian.net/browse/HSEARCH-2696.

**Comment by yrodiere** [comment]
Looks good, merged!

**Pull request merged**
