### PR TITLE
HSEARCH-4281 Fix tests for outbox event processing using different databases

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4281

### CODE REVIEW

**Comment by fax4ever** [comment]
Run a full build: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2634/2/pipeline

**Comment by fax4ever** [comment]
I dropped the commit:
> Reduce outbox processing transaction scope

and run a new full build again: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2634/4/pipeline

**Comment by fax4ever** [comment]
We got:
``` bash
[ERROR] DOCKER> I/O Error [Unable to pull 'docker.elastic.co/elasticsearch/elasticsearch:7.10.0' from registry 'docker.elastic.co' : {"message":"Head \"https://docker.elastic.co/v2/elasticsearch/elasticsearch/manifests/7.10.0\": Get \"https://docker-auth.elastic.co/auth?scope=repository%3Aelasticsearch%2Felasticsearch%3Apull&service=token-service\": dial tcp: lookup docker-auth.elastic.co: no such host"} (Internal Server Error: 500)]
```
that will be solved by https://github.com/hibernate/hibernate-search/pull/2633

Going to run a new full build again

**Comment by fax4ever** [comment]
https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2634/5/pipeline

**Comment by yrodiere** [comment]
Looking good; merged, thanks!
I'll append a commit to add a comment to the `setLockMode`.

**Comment by fax4ever** [comment]
Thanks!

**Pull request merged**
