### PR TITLE
HSEARCH-4015 Remove legacy dependecies from parent pom

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4015

### CODE REVIEW

**Comment by yrodiere** [comment]
@fax4ever Did you try building with `-Dlegacy.skip=false`? If the legacy module relies on this dependency management, you cannot remove it. At most you can move the dependency management to `legacy/pom.xml`.

**Comment by fax4ever** [comment]
I didn't know that we could compile, build and install the legacy module... There is any utility on doing that?

**Comment by yrodiere** [comment]
Just to make sure the code we're copying (from time to time) still works. It runs on CI only.

**Comment by yrodiere** [comment]
Merged, thanks

**Pull request merged**
