### PR TITLE
HSEARCH-2070 Using TypeMetadata API instead of IndexedTypeDescriptor API

### PR DESCRIPTION
**Pull request by fenrhil**

### CODE REVIEW

**Comment by gsmet** [comment]
Pull request updated with a fix following @gunnarmorling 's advice.

**Comment by Sanne** [comment]
thanks @gsmet and @fenrhil I'm mostly away today and tomorrow but will make sure these faceting fixes are included in the next 5.5.2

**Comment by gsmet** [comment]
Hi @Sanne!

Nice, thanks. I pushed some additional fixes for @DavideD to HSEARCH-2069.

**Comment by Sanne** [comment]
looks great, I'm merging it. Thanks a lot!

**Pull request closed without merging**
