### PR TITLE
HSEARCH-3030 + HSEARCH-3022 Remove the JGroups WildFly feature pack and Upgrade integration tests to WildFly 12

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-3022

@Sanne Regarding HSEARCH-3030, we can cancel it if you found a way to get JGroups 4 working, but otherwise it is probably our easiest way out.

### CODE REVIEW

**Comment by Sanne** [comment]
Great, thanks @yrodiere . Having this PR will allow to keep monitoring my changes in the ORM modules :+1: 

Do you mind if we wait a week to actually merge it? I had done some progress on the JGroups 4 upgrade, but couldn't finish it as I had to work on other ORM tasks.

**Comment by yrodiere** [comment]
@Sanne No problem, let's wait. We cannot release until Hibernate ORM is released anyway, so there's no rush.

**Comment by Sanne** [comment]
right, that's what I thought. Thanks! Useful to have this around already.

**Comment by Sanne** [comment]
superseded (and rebased into) pr #1652

**Pull request closed without merging**
