### PR TITLE
HSEARCH-3341 Do not send SUCCESS notifications when a  Jenkins pipeline build fails or is cancelled

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-3341

This one is a bit embarrassing... I tested it, it should work now: I got a FAILURE notification for http://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-yoann/detail/ci-test-this-please/8/pipeline .

### CODE REVIEW

**Comment by yrodiere** [comment]
... And it doesn't work for cancelled builds. Having a look.

**Comment by yrodiere** [comment]
Ok, so apparently it's not possible to distinguish between cancelled builds and failing builds, because of [this bug](https://issues.jenkins-ci.org/browse/JENKINS-28822). So any cancelled build will be notified as a failure.

I'd say it's close enough.

**Comment by gsmet** [comment]
Looks good to me.

**Comment by yrodiere** [comment]
Merged, thanks.

**Pull request merged**
