### PR TITLE
HSEARCH-3694 Support distance sorts on single-valued fields in nested documents

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-3694
https://hibernate.atlassian.net/browse/HSEARCH-3193

~~Preview because:~~
1. ~~Still need to uncomment a sort by distance there when this ticket is fixed in showcase~~ not possible, since the sort is a multi valued-field sort. Just updated the Jira key in the last commit.
2. ~~I would try to use the same comparator for not nested field too~~ done!

### CODE REVIEW

**Comment by yrodiere** [comment]
Looks good to me so far, apart from the Sonar issue.

**Comment by fax4ever** [comment]
Thanks @yrodiere the sonar issue is solved by another commit. I kept a not used null on purpose. More commits are coming...

**Comment by fax4ever** [comment]
Done the other stuff here. [This](https://ci.hibernate.org/job/hibernate-search/job/PR-2110/13/) is the build for all supported environments. I have not anything to add, so it is ready for review and potentially mergable.

**Comment by fax4ever** [comment]
Updated the branch with the last commit. A new with-all-supported-envs build is [here](https://ci.hibernate.org/job/hibernate-search/job/PR-2110/15/).

**Comment by yrodiere** [comment]
Merged, thanks!

**Comment by fax4ever** [comment]
Thank you!

**Pull request merged**
