### PR TITLE
HSEARCH-1875 Upgrade to JBoss Byteman 3.0.0

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HSEARCH-1875

### CODE REVIEW

**Comment by Sanne** [comment]
retest this please

**Comment by Sanne** [comment]
This also fixed: https://hibernate.atlassian.net/browse/HSEARCH-1854

**Comment by gunnarmorling** [comment]
Jenkins, retest this please.

**Comment by gunnarmorling** [comment]
@Sanne Any idea what's the test failure about?

**Comment by Sanne** [comment]
> Any idea what's the test failure about?

actually, no idea. I wish I could reproduce it locally. Let's not integrate this yet, I'll move it to the next release.

**Comment by gunnarmorling** [comment]
Jenkins, retest this please.

**Comment by Sanne** [comment]
What's the status here? Still failing just on Mac?

**Comment by hferentschik** [comment]
>  Still failing just on Mac?

does it. Works fine for me

I'll push a re-based version and let CI do another pull request build

**Pull request closed without merging**
