### PR TITLE
HSEARCH-4981 Use shorter transactions/wait longer for indexing to complete

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HSEARCH-4981

### CODE REVIEW

**Comment by marko-bekhta** [comment]
I was looking into test failures in the CockrachDB image update PR here https://ci.hibernate.org/job/hibernate-search/job/dependabot%252Fdocker%252Fbuild%252Fcontainer%252Fdatabase%252Fdatabase-containers-fd17be3f63/3/#showFailuresLink
I'm not convinced that these changes will solve our problems with these tests on CockroachDB 😔🙈😃, but I actually even got similar failures locally a few times, but not after the changes, so just want to see how it'll run on CI.

**Review by yrodiere — APPROVED** [review]
Alright, let's try this. Thanks.

**Comment by marko-bekhta** [comment]
thanks! since it passed on CI and you didn't find any apparent problems with the changes 🙈 let's give it one more run on CI and if that passes again -- merge it?

**Comment by yrodiere** [comment]
> thanks! since it passed on CI and you didn't find any apparent problems with the changes 🙈 let's give it one more run on CI and if that passes again -- merge it?

Works for me!

**Pull request merged**
