### PR TITLE
HSEARCH-2806 Remove method org.hibernate.search.engine.spi.EntityIndexBinding.getIndexManagers

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-2806

### CODE REVIEW

**Comment by Sanne** [comment]
Did you happen to "evaluate the impact" on Infinispan?

**Comment by yrodiere** [comment]
@Sanne I thought you created the ticket because it became doable in Infinispan...
I'll have a look. Version 9.1 only, right?

**Comment by yrodiere** [comment]
@Sanne Infinispan master can compile with a few changes, at least: https://github.com/yrodiere/infinispan/tree/HSEARCH-2806
I can't easily build it on our CI, I'll have a look on Monday.

**Comment by Sanne** [comment]
I trust that it's possible but I'm slightly concerned for 2 reasons:
 - the resulting code on Infinispan looks even less compelling -> should we improve our API?
 - they shipped the 9.1.0.Final already -> not really "our problem" but we could try to be nice neighbours: they probably expect component upgrades to be drop-in compatible now.

No "vetoing" this change but is it worth it?

**Comment by yrodiere** [comment]
> No "vetoing" this change but is it worth it?

Personally I don't care, I just worked on this because you added a ticket for it in 5.8. We can postpone it to 6.

**Comment by yrodiere** [comment]
FYI, the Infinispan tests pass even after the changes: http://ci.hibernate.org/job/infinispan-yoann/3/
There are some test failures, but they seem unrelated.

**Comment by Sanne** [comment]
merged this! Let's keep your Infinispan branch around..

**Pull request closed without merging**
