### PR TITLE
HSEARCH-4244 Migration guide from 6.0 to 6.1

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-4244

### CODE REVIEW

**Review by fax4ever — COMMENTED** [review]
It looks good to me.
I would just advise to add link to the Migration guide from 5.x to 6.1,
in case the user needs to move directly from 5.x to 6.1.

**Comment by yrodiere** [comment]
Merged, thanks.

There is no migration guide from 5.x to 6.1, and there won't be. People wanting to migrate from 5.x to 6.1 will have to move to 6.0 first, then to 6.1, as explained in the guide.

**Comment by fax4ever** [comment]
Sorry I meant
> I would just advise to add link to the Migration guide from 5.x to 6.**0**

Just why the user have to move to 6.0 first, then to 6.1, I would add the link.

**Comment by yrodiere** [comment]
There already is such a link:

```
If you're looking to migrate from an earlier version,
you should migrate step-by-step, from one minor version to the next,
following the migration guide of link:https://hibernate.org/search/documentation/[each version].
```

**Pull request merged**
