### PR TITLE
HSEARCH-2007 Adding Maven Clirr plug-in configuration

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
When running `mvn clirr:clirr -pl engine`

I get

```
$ mvn clirr:clirr -pl engine
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Scanning for projects...

------------------------------------------------------------------------
Building Hibernate Search Engine 5.6.0-SNAPSHOT
------------------------------------------------------------------------

>>> clirr-maven-plugin:2.6.1:clirr (default-cli) > compile @ hibernate-search-engine >>>

--- build-helper-maven-plugin:1.9.1:parse-version (parse-version) @ hibernate-search-engine ---

--- maven-enforcer-plugin:1.3.1:enforce (enforce-rules) @ hibernate-search-engine ---

--- maven-processor-plugin:2.2.4:process (process) @ hibernate-search-engine ---
diagnostic: warning: [options] bootstrap class path not set in conjunction with -source 1.7

--- maven-resources-plugin:2.6:resources (default-resources) @ hibernate-search-engine ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 3 resources

--- maven-compiler-plugin:3.1:compile (default-compile) @ hibernate-search-engine ---
Changes detected - recompiling the module!
Compiling 585 source files to /Users/emmanuel/Code/search/engine/target/classes
bootstrap class path not set in conjunction with -source 1.7
/Users/emmanuel/Code/search/engine/src/main/java/org/hibernate/search/indexes/impl/IndexManagerHolder.java: Some input files use or override a deprecated API.
/Users/emmanuel/Code/search/engine/src/main/java/org/hibernate/search/indexes/impl/IndexManagerHolder.java: Recompile with -Xlint:deprecation for details.
/Users/emmanuel/Code/search/engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java: Some input files use unchecked or unsafe operations.
/Users/emmanuel/Code/search/engine/src/main/java/org/hibernate/search/engine/spi/DocumentBuilderIndexedEntity.java: Recompile with -Xlint:unchecked for details.

--- maven-injection-plugin:1.0.2:bytecode (default) @ hibernate-search-engine ---
writing injection changes back [/Users/emmanuel/Code/search/engine/target/classes/org/hibernate/search/engine/Version.class]

--- forbiddenapis:1.8:check (verify-forbidden-apis) @ hibernate-search-engine ---
Scanning for classes to check...
Reading bundled API signatures: jdk-unsafe
Reading bundled API signatures: jdk-deprecated
Reading bundled API signatures: jdk-system-out
Loading classes to check...
Scanning for API signatures and dependencies...
Scanned 746 (and 612 related) class file(s) for forbidden API invocations (in 0.39s), 0 error(s).

<<< clirr-maven-plugin:2.6.1:clirr (default-cli) < compile @ hibernate-search-engine <<<

--- clirr-maven-plugin:2.6.1:clirr (default-cli) @ hibernate-search-engine ---
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 6.537 s
Finished at: 2015-09-18T13:41:04+02:00
Final Memory: 42M/488M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:clirr-maven-plugin:2.6.1:clirr (default-cli) on project hibernate-search-engine: The skin does not exist: Failure to find org.apache.maven.skins:maven-default-skin:jar:1.1 in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
mvn deploy:deploy-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]


org.apache.maven.skins:maven-default-skin:jar:RELEASE

from the specified remote repositories:
sonatype (https://oss.sonatype.org/content/repositories/snapshots/, releases=true, snapshots=true),
jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/, releases=true, snapshots=true),
central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by gunnarmorling** [comment]
@emmanuelbernard, interesting, never seen that before. Just an idea, can you try without your colouring extension?

**Comment by Sanne** [comment]
I'm having the same problem, not using the colouring extension.

**Comment by gunnarmorling** [comment]
Hum, weird. The skin artifact is in Maven Central for sure: http://repo1.maven.org/maven2/org/apache/maven/skins/maven-default-skin/1.1/.

Do you happen to have any special repo config by any chance? Btw. I am not sure whether this skin stuff is loaded through the dependency or plug-in repo, may be worth double-checking both.

**Comment by Sanne** [comment]
@gunnarmorling I've been trying again several repo combinations, including a "full clean build", I keep having the same error. That skin is not being downloaded for some reason, I'd like to understand why that works for you.
Could you try to move your local cache away to some hidden (but safe to restore later) place?

**Comment by gunnarmorling** [comment]
@Sanne Just removed the skin from my local Maven repo and it's getting downloaded again:

    [INFO] --- clirr-maven-plugin:2.6.1:clirr (default-cli) @ hibernate-search-engine ---
    Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/skins/maven-default-skin/maven-metadata.xml
    Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/skins/maven-default-skin/maven-metadata.xml (370 B at 0.4 KB/sec)
    Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/skins/maven-default-skin/1.1/maven-default-skin-1.1.jar
    Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/skins/maven-default-skin/1.1/maven-default-skin-1.1.jar (13 KB at 124.9 KB/sec)

Out of interest, what Maven version are you on? Do you see anything special when running with the "-X" option?

**Comment by gunnarmorling** [comment]
FWIW, works for me with both Maven 3.2.5 and 3.3.3. Really weird.

**Comment by DavideD** [comment]
This works for me.

Is it ok if I merge it?

**Comment by Sanne** [comment]
Let me try it again..

**Comment by Sanne** [comment]
So, now it fails but only if I keep my custom `settings.xml` around which enabled the JBoss repository.

    [ERROR] Failed to execute goal org.codehaus.mojo:clirr-maven-plugin:2.6.1:clirr (default-cli) on project hibernate-search-engine: The skin does not exist: Could not find artifact org.apache.maven.skins:maven-default-skin:jar:1.1 in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/)

If I move the `settings.xml` away, it runs correctly.

Not sure what to think of that? Something corrupt in the `jboss-public-repository-group` ?

**Comment by Sanne** [comment]
@gunnarmorling up to you. If you think this is useful, go ahead and merge it. We'll have to remember about this issue to disable the wrong repositories when using it.

**Comment by DavideD** [comment]
Is it you settings similar to the settings-example.xml? Because it works for me if I use it.
Is the clirr configuration in master working for you?

I would be prone to include it anyway and move on.

**Comment by Sanne** [comment]
@DavideD yes it works if I use the `settings-example.xml`.

I then tried to break down my `settings.xml`, to keep my UK mirror settings but still disable the jboss.org repository, and it got to download the missing pieces and worked.
I now restored by jboss.org setting, and it still works.. I'm confused as I'm pretty sure it shouldn't be working like that. But I guess now it will just work for me..

**Comment by DavideD** [comment]
Ok, I'm going to merge it then

**Comment by Sanne** [comment]
+1
If we ever hit that problem again, we should know what to do about it.

**Comment by gunnarmorling** [comment]
Cool, thanks! Btw. I am looking into alternative tools, as Clirr is basically unmaintained for quite a while now, so its reports are a bit lacking if it comes to new language features. Revapi for instance looks promising. Anyways +1 for moving forward with what we have, and we can take it from there. Thanks!

**Comment by DavideD** [comment]
Merge it on master https://github.com/hibernate/hibernate-search/pull/928

Should I also merge it on 5.5?

**Comment by Sanne** [comment]
> +1 for moving forward with what we have, and we can take it from there. 

I like that spirit :)

> Should I also merge it on 5.5?

No, I wouldn't waste cycles on that

**Comment by Sanne** [comment]
hey! make sure you mark JIRA issues resolved when merging fixes.

**Pull request closed without merging**
