### PR TITLE
HSEARCH-4024 Upgrade integration tests to the latest version of Spring Boot

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-4024

According to [this page](https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started.html#:~:text=Spring%20Boot%202.3.,Spring%20Framework%205.2.) the new version of Spring Boot should support JDK-14.

### CODE REVIEW

**Comment by fax4ever** [comment]
I converted to draft, since it seems that we have some issue with JUnit...

**Comment by fax4ever** [comment]
I found this option: https://stackoverflow.com/a/64371503/1812965.

**Comment by fax4ever** [comment]
Let's try a full build: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2406/3/pipeline.

**Comment by fax4ever** [comment]
Started a [new full-build](https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2406/5/pipeline).
The #3 has some issue with the connections I think..

**Comment by yrodiere** [comment]
>  The #3 has some issue with the connections I think.

It failed because you force-pushed and Jenkins couldn't find the commit to build anymore ;)

Looks good to me, feel free to merge once the build succeeds. Thanks!

**Comment by fax4ever** [comment]
Thanks for the explanation! I'll merge as soon as the CI passes.

**Comment by fax4ever** [comment]
We have a failure for the JDK-16 profile... I'm looking at...

**Comment by fax4ever** [comment]
I disabled the IT with Spring and JDK-16 profile and run a new full-build: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search/detail/PR-2406/7/pipeline.

**Comment by yrodiere** [comment]
Merged, thanks!

**Pull request merged**
