### PR TITLE
HSEARCH-4170 Upgrade to Elasticsearch 7.11

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-4170

Full build here: https://ci.hibernate.org/blue/organizations/jenkins/hibernate-search-personal-yoann/detail/HSEARCH-4170/9/pipeline

### CODE REVIEW

**Comment by gsmet** [comment]
Isn't 7.11 the first non-Open Source version?

Do we really want to do that and make a non Open Source software our default setup? I know the low level client is still Open Source but I'm not sure it's a good idea to continue supporting non-OSS versions of Elasticsearch (and in any case, I wouldn't make it the default test setup).

**Comment by gsmet** [comment]
My rationale is that if no Open Source tools support 7.11+, at some point, they might have to reconsider things.

**Comment by yrodiere** [comment]
> Isn't 7.11 the first non-Open Source version?

It is.

> Do we really want to do that and make a non Open Source software our default setup?

Well, I mainly want to test it now that it's out. As to making it the default... I guess I can revert that. I'll add a commit.

> My rationale is that if no Open Source tools support 7.11+, at some point, they might have to reconsider things.

In an ideal world, yes. I don't share your optimism, though.

I could be persuaded not to advertise 7.11 support, but I don't think not supporting it at all would be a good thing for Hibernate Search.

For now I'll make 7.10 the default for testing and I will add warnings in the documentation about 7.11 not being open-source.

**Comment by yrodiere** [comment]
> For now I'll make 7.10 the default for testing and I will add warnings in the documentation about 7.11 not being open-source.

Done. Does it look like a good compromise, @gsmet?

**Review by gsmet — APPROVED** [review]

**Pull request merged**
