### PR TITLE
HSEARCH-1302 Test match on stopwords-only full-text field

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HSEARCH-1302

I just added a test for it

### CODE REVIEW

**Comment by yrodiere** [comment]
@fax4ever How is this test different from `org.hibernate.search.integrationtest.backend.tck.search.predicate.AbstractPredicateSimpleAnalysisIT#noTokenAfterAnalysis`?

**Comment by fax4ever** [comment]
In new test we have a document with a field having all stopwords... So the stopwords are provided at writing time.

**Comment by yrodiere** [comment]
> In new test we have a document with a field having all stopwords... So the stopwords are provided at writing time.

I believe in `org.hibernate.search.integrationtest.backend.tck.search.predicate.AbstractPredicateSimpleAnalysisIT#noTokenAfterAnalysis` too, there is an indexed document containing the stopword we're looking for. See `org.hibernate.search.integrationtest.backend.tck.search.predicate.AbstractPredicateSimpleAnalysisIT.DataSet#analyzedFieldValues`.

If there really is a problem with the existing test, I'd recommend improving it rather than creating a new one. Backend tests are notoriously slow to start...

If there's no problem with the existing test, we can simply drop this PR :) The best code is the one you don't have to write!

**Comment by fax4ever** [comment]
You're right we already cover this case with this test! Let's close this PR!

**Pull request closed without merging**
