### PR TITLE
HSEARCH-2262 In the Elasticsearch mapping, validate the type of the null_value/indexNullAs property

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-2262

~~This currenly only works when running on JVMs with UTC timezone, and will fail miserably on JVMs with GMT+1 default timezone for instance. Either we fix [HSEARCH-2335](https://hibernate.atlassian.net/browse/HSEARCH-2335) and this PR will work as is, or we decide not to, and this PR will need some work.~~ Fixed, see comments.

### CODE REVIEW

**Comment by Sanne** [comment]
This isn't waiting on any other open PR right?

**Comment by yrodiere** [comment]
@Sanne This currently doesn't work, as explained in the first comment. It's not waiting on a PR alright, but it's waiting on HSEARCH-2335, which hasn't been fixed yet and must be fixed before merging.

**Comment by Sanne** [comment]
ok. Do you plan to take HSEARCH-2335 ?

**Comment by yrodiere** [comment]
Well, it's basically a behavior change that fixes some bugs, but *will*
introduce ascending compatibility issues... Which is why I didn't address
it right away. Maybe you can give your opinion on that one? I think it
should be addressed, but someone else may think it's invalid ("works as
expected")...

If it's deemed valid, of course I can take it as soon as I'm done with the
VALIDATE/schema export stuff on Elasticsearch.

Yoann Rodière <yrodiere@redhat.com>
Software Engineer
Red Hat / Hibernate NoORM Team

**Comment by yrodiere** [comment]
See the discussion in https://hibernate.atlassian.net/browse/HSEARCH-2335: I was wrong. I will fix the tests so that they don't rely on the local timezone anymore, and will tackle https://hibernate.atlassian.net/browse/HSEARCH-2355 later.

**Comment by yrodiere** [comment]
The tests have been fixed. Ready for review!

**Comment by Sanne** [comment]
Nice one, merging. The only thing which got me a bit confused is the usage of test Suite to make the two tests :)

**Comment by Sanne** [comment]
merged

**Pull request closed without merging**
