### PR TITLE
HSEARCH-2869 Some tickets are missing in the release notes

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HSEARCH-2869

### CODE REVIEW

**Comment by yrodiere** [comment]
To be backported to 5.5, 5.6, 5.7. Backports are available there:

 * https://github.com/yrodiere/hibernate-search/tree/HSEARCH-2869-5.7
 * https://github.com/yrodiere/hibernate-search/tree/HSEARCH-2869-5.6
 * https://github.com/yrodiere/hibernate-search/tree/HSEARCH-2869-5.5

**Comment by Sanne** [comment]
I hope you automated this?!

**Comment by Sanne** [comment]
sorry I won't apply it to 5.5, it's too much paperwork to do and it's hopefully a dead branch in terms of maintenance.

**Comment by Sanne** [comment]
merged! (except on branch 5.5)

**Comment by yrodiere** [comment]
Thanks! About 5.5, ok, I understand.
I didn't automate the work, but I only had to search for the ticket number in the git log in order to find out in which version each ticket was solved, so it wasn't too much work in the end.

**Pull request closed without merging**
