### PR TITLE
HSEARCH-5050 Update link to documentation for batch_fetch_size in Hibernate ORM 6.4+

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-5050

### CODE REVIEW

**Review by marko-bekhta — APPROVED** [review]
🎉

**Comment by marko-bekhta** [comment]
Maybe let's also backport it to 7.0?

**Comment by yrodiere** [comment]
Sure, I'll push that directly. Thanks.

**Comment by marko-bekhta** [comment]
nice 😃 thanks!

**Pull request merged**
