### PR TITLE
HSEARCH-3035 Use source and target properties for JBoss logging processor

### PR DESCRIPTION
**Pull request by gsmet**
https://hibernate.atlassian.net/browse/HSEARCH-3035

### CODE REVIEW

**Comment by gsmet** [comment]
The build failed because the new version of hibernate common annotations is not yet synced to Central.

**Comment by Sanne** [comment]
Why do you need this?

**Comment by gsmet** [comment]
Why do I need what? This commit? I thought it would be better to use the properties.

**Comment by Sanne** [comment]
I'm wondering what's the reason to force the annotation processor to use the same as the main compiler version; while I understand that typically they are the same this isn't a given, so I'm curious why you feel this is a change which needs to be done.

**Comment by Sanne** [comment]
(BTW just being curious - I see no problem with it either, so go ahead if that's what you prefer)

**Comment by yrodiere** [comment]
Merged, thanks!

**Comment by gsmet** [comment]
@Sanne Well, it's mostly to avoid updating them when we will update the source/target versions at some point.

We can still use specific versions if need be but in the default case they will be consistent, which I think is an improvement.

**Comment by Sanne** [comment]
Ok. Just remember not all annotation processors work equally well on all JDKs ;)

**Pull request merged**
