### PR TITLE
Get build to pass on JDK9 preview 9-ea+120

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HSEARCH-2290

### CODE REVIEW

**Comment by Sanne** [comment]
I had to update it. Please make sure you merge the latest.

**Comment by gsmet** [comment]
Merged! Thanks!

**Comment by Sanne** [comment]
@gsmet don't forget to mark related JIRA issues resolved ;)

thanks!

**Comment by gsmet** [comment]
Oh, yes, sorry, missed this one!

**Pull request closed without merging**
