### PR TITLE
Upgrading ORM version, and deadlock with MariaDB tests resolved

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HSEARCH-2379
 - https://hibernate.atlassian.net/browse/HSEARCH-2499

### CODE REVIEW

**Comment by Sanne** [comment]
N.B. the ORM upgrade is not going to the 5.7 branch (neither now nor later).

For the test fix, I have a better solution too coming which requires Java 8 (also restricted to 5.7 only)

A preview is here:
 96ad5f727b189ecc3d2b89cae61589d805847703

**Comment by yrodiere** [comment]
Rebased and merged, thanks!

**Comment by Sanne** [comment]
thanks, I'll re-enable the mariadb tests on ci.hibernate.org

**Comment by Sanne** [comment]
thanks, I'll re-enable the mariadb tests on ci.hibernate.org

**Pull request merged**
