### PR TITLE
HSEARCH-2561 Allow sorting metadata to be overriden during query execution

### PR DESCRIPTION
**Pull request by yrodiere**
~~This PR is based on #1299 (HSEARCH-2570), which we'll have to merge first.~~ => Merged!

Relevant JIRA ticket: https://hibernate.atlassian.net/browse/HSEARCH-2561

### CODE REVIEW

**Comment by Sanne** [comment]
@anistor this is looking good to me. Do you want to try it out on Infinispan to see how it works in practice?

**Comment by anistor** [comment]
I'm trying it out now. Might now have results until later today (as we have long planning meeting today).

**Comment by yrodiere** [comment]
@anistor Any news on this?

**Comment by Sanne** [comment]
Doesn't seem very dangerous; I'll merge it, so we can keep working with minimal conflicts. @anistor will be able to open bugs as needed.

**Pull request closed without merging**
