### PR TITLE
HSEARCH-2630 and HSEARCH-2631 Some uses of full text queries will corrupt object loading statistics

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HSEARCH-2630
https://hibernate.atlassian.net/browse/HSEARCH-2631

### CODE REVIEW

**Comment by yrodiere** [comment]
Note: we should backported this to 5.7, and maybe also to 5.6.

**Comment by yrodiere** [comment]
I just spotted another case where we have a similar problem; will push an update.

**Comment by yrodiere** [comment]
Done; I added a test and fix for HSEARCH-2631.

**Comment by Sanne** [comment]
nice. Merged in master, backporting now..

**Comment by Sanne** [comment]
backported to both 5.6 and 5.7 branches. Branch 5.6 needed a little change as `Session` didn't implement the JPA flavoured `getResultList()` method yet.

Thanks!

**Pull request merged**
