### PR TITLE
HSEARCH-1917 Don't add null or empty values to the facet field

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by Sanne** [comment]
great! merged, but also backporting to 5.5 now..

**Comment by xyloman** [comment]
We recently started upgrading to hibernate search 5.5 from 5.0 and ran into this same issue.  What is the timeline for releasing the backport version 5.5.3.Final as this is blocking our upgrade plans.

**Comment by Sanne** [comment]
@xyloman good to now!

We can make a release happen soon; With some luck I could manage tomorrow, otherwise beginning of next week should be possible.

**Comment by Sanne** [comment]
Hello, it was released yesterday.

**Pull request closed without merging**
