### PR TITLE
HSEARCH-4752 Bump Elasticsearch version to test against the latest micro 8.5.2

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HSEARCH-4752
https://hibernate.atlassian.net/browse/HSEARCH-4754

The bug with the scaled_float property hasn't been fixed yet, so I've updated `supportsMatchOnScaledNumericLossOfPrecision` to include this new version.

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by marko-bekhta** [comment]
Hmm, so this is failing on a test for timezones, and the sad part is that I cannot reproduce this locally. the documents that it is failing on are:
```json
"hits": [
      {
        "_index": "singlefield-000001",
        "_id": "ZonedDateTime_doc_42",
        "_score": 1.0,
        "_routing": "ZonedDateTime",
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000Z[UTC]",
          "_entity_type": "singleFieldType"
        }
      },
      {
        "_index": "singlefield-000001",
        "_id": "ZonedDateTime_doc_44",
        "_score": 1.0,
        "_routing": "ZonedDateTime",
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000-08:00[America/Los_Angeles]",
          "_entity_type": "singleFieldType"
        }
      }
    ]
```

**Comment by gsmet** [comment]
Yeah, when you have these sort of problems, you need to find out what is the CI time zone to try to reproduce locally.

But these problems are usually tricky and it might be a bug in Elasticsearch.

**Comment by gsmet** [comment]
@marko-bekhta there is a .2 now, maybe it fixes the issue we have?

**Comment by marko-bekhta** [comment]
@gsmet thanks! let me take a look 😃

**Comment by marko-bekhta** [comment]
And it successfully failed 🥲 I've looked at the release notes https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.5.1.html and cannot see any obvious culprits. The good news is - I've found out that the data generated on CI differs from what I got locally. Here are the failing objects from CI:
```json
      {
        "_index": "singlefield-000001",
        "_id": "ZonedDateTime_doc_42",
        "_score": 1.0,
        "_routing": "ZonedDateTime",
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000Z[UTC]",
          "_entity_type": "singleFieldType"
        }
      },
      {
        "_index": "singlefield-000001",
        "_id": "ZonedDateTime_doc_44",
        "_score": 1.0,
        "_routing": "ZonedDateTime",
        "_source": {
          "field0_ZonedDateTime": "1900-01-01T00:00:00.000000000+00:19:32[Europe/Amsterdam]",
          "_entity_type": "singleFieldType"
        }
      },
```
I'll try to reproduce the problem locally, and if it won't work on 8.5.1 but will be fine on previous versions 8.5.0/8.4, I'll report a bug to ES and will add an "exception" to `ElasticsearchTckBackendFeatures` so that this test won't fail the builds

**Comment by marko-bekhta** [comment]
Hey Guillaume! After trying to pin down the root cause of that failing test, it looks like the issue comes from the JDK. I think that for now, it's OK to have that specific Amsterdam timezone replaced with something else. And I'll create a ticket to run this test against all time zones eventually. I've tried to use a different/older JDK (not the bundled one) with 8.5.1 and wasn't able to reproduce the issue. And I'm subscribed to the ES issue so I'll keep an eye on it. I'll start a build against all ES we test to see if all is OK.

**Pull request merged**
