### PR TITLE
Hsearch 1987

### PR DESCRIPTION
**Pull request by Sanne**
building on #920 : added one more fix and saved a bit of memory

### CODE REVIEW

**Comment by Sanne** [comment]
Removed the last commit. Still need to process the other remark..

**Comment by gunnarmorling** [comment]
@Sanne You still plan to follow-up on this? Or should I take it over again? Is there anything else missing for the release?

**Comment by Sanne** [comment]
Hi Gunnar,
I could not follow up on that last issue with ids, I think it's ok to open
that as a separate issue to be looked at later on. Could you open the jira
and describe it please (I don't have my IDE now and don't remember the
details).

Shall we merge this then? Your fix looks good for the issue at hand.

**Comment by gunnarmorling** [comment]
Rebased and applied. I've added one more commit to fix the remaining issue about numeric embedded id fields. All should be good now. Cheers :)

**Pull request closed without merging**
