### PR TITLE
HSEARCH-2406 Execute -engine tests against Elasticsearch too

### PR DESCRIPTION
**Pull request by yrodiere**
~This PR is based on  #1222 (HSEARCH-2360), which will have to be merged first.~ => Done!

Relevant tickets:
 * https://hibernate.atlassian.net/browse/HSEARCH-2406
 * https://hibernate.atlassian.net/browse/HSEARCH-2392 (because the fix was also needed for HSEARCH-2406)

Nothing much to say, except that some bugs were uncovered and will have to be fixed (see the linked tickets in [HSEARCH-2406](https://hibernate.atlassian.net/browse/HSEARCH-2406)). There weren't many of them, though :)

### CODE REVIEW

**Comment by yrodiere** [comment]
Actually, it seems some tests are failing randomly (namely `org.hibernate.search.test.projection.ProjectionConversionTest.concurrentMixedProjections()`). I'll have a look.

**Comment by yrodiere** [comment]
I ignored the test and created https://hibernate.atlassian.net/browse/HSEARCH-2484 .

**Comment by yrodiere** [comment]
Rebased and ready for review!

**Comment by DavideD** [comment]
Rebased and merged https://github.com/hibernate/hibernate-search/pull/1224,
thanks

**Pull request closed without merging**
